import {writeFileSync} from 'node:fs';
import {icon,ICON_NAMES} from './ui-icons.js';

// Export the same geometry used by the game; avoid a second, drifting icon set.
const materials='.icon-base{fill:#afc0a0;stroke:none;stroke-width:1.6;stroke-linejoin:round}.icon-detail{fill:none;stroke:#c5d3b9;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}.icon-accent{fill:#d8ae68}.icon-cut{fill:#142825}';
const paths=name=>icon(name).replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');
export function exportBrandAssets(){
 writeFileSync('assets/obitel-icons.svg','<svg xmlns="http://www.w3.org/2000/svg"><defs><style>'+materials+'</style>'+ICON_NAMES.map(name=>'<symbol id="'+name+'" viewBox="0 0 24 24">'+paths(name)+'</symbol>').join('')+'</defs></svg>');
 const colors=[['Чернила','#0d1b1c'],['Панель','#192d2c'],['Олива','#70866a'],['Шалфей','#afc0a0'],['Янтарь','#d8ae68'],['Слоновая кость','#eee3c8']];
 writeFileSync('assets/brand-board.html',`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Обитель — фирменный стиль</title><style>
 *{box-sizing:border-box}body{margin:0;padding:40px;background:#0d1b1c;color:#eee3c8;font:14px/1.5 system-ui,sans-serif}main{max-width:1000px;margin:auto}header{display:flex;align-items:center;gap:24px;border-bottom:1px solid #536653;padding-bottom:24px}header img{width:96px;height:96px}h1{margin:0;font-size:32px}p{color:#afc0a0}h2{font-size:20px;margin-top:32px}.palette,.icons{display:grid;gap:12px}.palette{grid-template-columns:repeat(6,minmax(0,1fr))}.palette article,.icons article{background:#192d2c;border:1px solid #536653;border-radius:8px;padding:14px}.swatch{height:42px;border:1px solid #536653;border-radius:4px;margin-bottom:10px}code{display:block;font-size:12px}.icons{grid-template-columns:repeat(auto-fit,minmax(125px,1fr))}.icons article{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.icons svg{width:22px;height:22px;flex-shrink:0}.icons .small{width:18px;height:18px}.icons code{width:100%;color:#afc0a0}${materials}@media(max-width:640px){body{padding:20px}.palette{grid-template-columns:repeat(3,1fr)}h1{font-size:24px}}
 </style><main><header><img src="obitel-emblem.svg" alt="Эмблема Обители"><div><h1>ОБИТЕЛЬ МЁРТВЫХ</h1><p>Ворота убежища · визуальная система 0.12</p></div></header><h2>Фирменная палитра</h2><div class="palette">${colors.map(([name,color])=>`<article><div class="swatch" style="background:${color}"></div>${name}<code>${color}</code></article>`).join('')}</div><h2>Авторские векторные иконки · 22 / 18 px</h2><p>Единая сетка 24 × 24, открытые силуэты, линия 1.6, янтарный акцент. Геометрия совпадает с интерфейсом игры.</p><div class="icons">${ICON_NAMES.map(name=>'<article>'+icon(name)+icon(name).replace('class="','class="small ')+'<code>'+name+'</code></article>').join('')}</div></main></html>`);
}
