import {campaignState,milestoneView} from './campaign.js';
import {shelterIcon} from './ui-icons.js';
const rewardText=reward=>Object.entries(reward).map(([key,n])=>({scrap:'Детали',cloth:'Ткань',cores:'Ядра'}[key])+' +'+n).join(' · ');
export function renderCampaignSummary(root,save,onContinue,onJournal){
 const c=campaignState(save),ready=milestoneView(save).filter(m=>!m.claimed&&m.progress>=m.goal).length;root.innerHTML='<div class="campaign-seal">'+shelterIcon('guide')+'</div><div class="campaign-objective"><span class="eyebrow">МАРШРУТ ВЫЖИВШЕГО</span><h3>'+c.title+'</h3><p>'+c.description+'</p></div><div class="campaign-meter"><b>'+c.completed+'<small> / '+c.total+'</small></b><span>РАЙОНОВ ОСВОЕНО</span><div><i style="width:'+c.percent+'%"></i></div></div><button class="secondary" data-campaign="continue">'+(ready?'НАГРАДЫ · '+ready:c.action==='boss'?'К БОССУ':c.next?'К ЦЕЛИ':'В ЖУРНАЛ')+'</button>';root.querySelector('button').onclick=()=>ready?onJournal(true):c.next?onContinue(c):onJournal(false);
}
export function renderCampaignJournal(root,save,onMap,onRaids){
 const c=campaignState(save);root.innerHTML='<div class="chronicle-hero"><span class="eyebrow">КАМПАНИЯ · ВОССТАНОВЛЕНИЕ ГОРОДА</span><h2>Вернуть город живым.</h2><p>Освой восемь районов. Три победные вылазки и уровень района открывают босса; после победы получи его награду и двигайся дальше.</p><div class="city-route">'+c.districts.map(d=>'<button data-route="'+d.index+'" class="'+(d.done?'done':c.next?.index===d.index?'current':'')+'" aria-label="'+d.name+': '+d.status+'">'+String(d.index+1).padStart(2,'0')+'</button>').join('')+'</div><span class="route-caption">'+c.completed+' / 8 РАЙОНОВ ОСВОЕНО · '+(c.next?'УРОВЕНЬ '+c.next.level+' ДЛЯ СЛЕДУЮЩЕГО БОССА':'КАМПАНИЯ ЗАВЕРШЕНА')+'</span></div><div class="district-dossiers">'+c.districts.map(d=>'<article class="district-dossier '+(d.done?'done':'')+'"><div class="dossier-art" style="background-image:url(assets/district-'+d.index+'.webp)"><span>'+String(d.index+1).padStart(2,'0')+'</span><b>'+d.status+'</b></div><div class="dossier-body"><span class="eyebrow">'+d.role+'</span><h3>'+d.name+'</h3><p>Уровень '+d.level+' · Босс: '+d.boss+'</p><div class="district-stages">'+[1,2,3].map(n=>'<i class="'+(d.runs>=n?'done':'')+'"></i>').join('')+'<span>'+shelterIcon(d.done?'leaderboard':'raids')+'</span></div><small>'+d.runs+' / 3 ЗАЧИСТКИ · '+(d.done?'БОСС ПОВЕРЖЕН':'ПОБЕДИ БОССА ДЛЯ ПРОДОЛЖЕНИЯ')+'</small><button class="'+(d.open?'primary':'secondary')+'" data-dossier="'+d.index+'">'+(!d.open?'ТРЕБОВАНИЯ':d.status==='БОСС ДОСТУПЕН'?'К БОССУ':'ВЫБРАТЬ РАЙОН')+'</button></div></article>').join('')+'</div>';
 root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>onMap(Number(b.dataset.route)));
 root.querySelectorAll('[data-dossier]').forEach(b=>b.onclick=()=>{const d=c.districts[Number(b.dataset.dossier)];d.status==='БОСС ДОСТУПЕН'?onRaids(d.index):onMap(d.index)});
}
export async function renderMilestones(root,api,toast,onUpdate){
 root.innerHTML='<div class="chronicle-loading">Сверяем достижения с убежищем…</div>';
 try{const view=await api('operations');if(!root.isConnected)return;if(!view.milestones)throw new Error('Сервер обновляется. Повтори через минуту.');
 const claimed=view.milestones.filter(m=>m.claimed).length,ready=view.milestones.filter(m=>!m.claimed&&m.progress>=m.goal).length;
 root.innerHTML='<div class="chronicle-hero milestone-hero"><span class="eyebrow">ЛИЧНОЕ ДЕЛО · ПОСТОЯННЫЕ ЦЕЛИ</span><h2>Твой след в городе.</h2><p>Достижения не сбрасываются. Каждая награда выдаётся один раз, без дополнительного опыта.</p><div class="chronicle-totals"><b>'+claimed+' / '+view.milestones.length+'<small>НАГРАД ПОЛУЧЕНО</small></b><b>'+ready+'<small>МОЖНО ЗАБРАТЬ</small></b></div></div><div class="milestone-grid">'+[...view.milestones].sort((a,b)=>Number(a.claimed)-Number(b.claimed)||Number(b.progress>=b.goal)-Number(a.progress>=a.goal)).map(m=>'<article class="milestone-card '+(m.claimed?'claimed':m.progress>=m.goal?'ready':'')+'"><span class="milestone-emblem">'+shelterIcon(m.icon)+'</span><div><span class="eyebrow">'+(m.claimed?'ЗАПИСАНО В ЖУРНАЛ':m.progress>=m.goal?'ЦЕЛЬ ДОСТИГНУТА':'ПОСТОЯННАЯ ЦЕЛЬ')+'</span><h3>'+m.title+'</h3><p>'+m.description+'</p><div class="milestone-track" role="progressbar" aria-label="'+m.title+'" aria-valuenow="'+m.progress+'" aria-valuemin="0" aria-valuemax="'+m.goal+'"><i style="width:'+m.progress/m.goal*100+'%"></i></div><small>'+m.progress+' / '+m.goal+'</small></div><div class="milestone-reward"><b>'+rewardText(m.reward)+'</b><button class="'+(!m.claimed&&m.progress>=m.goal?'primary':'secondary')+'" data-milestone="'+m.id+'" '+(m.claimed||m.progress<m.goal?'disabled':'')+'>'+(m.claimed?'ПОЛУЧЕНО':m.progress<m.goal?'В ПРОЦЕССЕ':'ЗАБРАТЬ')+'</button></div></article>').join('')+'</div>';
 root.querySelectorAll('[data-milestone]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('operations/claim',{id:'milestone:'+b.dataset.milestone});toast('Достижение записано. Награда получена.');onUpdate()}catch(e){b.disabled=false;toast(e.message)}});
 }catch(e){if(root.isConnected){root.textContent=e.message;const retry=document.createElement('button');retry.className='secondary';retry.textContent='ПОВТОРИТЬ';retry.onclick=()=>renderMilestones(root,api,toast,onUpdate);root.append(retry)}}
}
