import {MAPS,playerLevel} from './balance.js';
import {medalMarkup,bindPlayerProfiles} from './player-profile-ui.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('ru-RU');
export async function clansUI(root,api,toast,openRaid){
 root.innerHTML='<p class="page-intro">Связываемся с кланами…</p>';
 try{
 const data=await api('clans');if(root.hidden)return;const c=data.clan;
 const row=(title,detail,buttons='')=>'<div class="clan-row"><div><strong>'+title+'</strong><small>'+detail+'</small></div>'+buttons+'</div>';
 const player=m=>'<button class="player-name-link" data-player="'+esc(m.code)+'">'+esc(m.name)+'</button>';
 const board=c?new Set(c.progress.display):new Set();
 const bossCard=b=>{const live=c.raids.find(r=>r.clan),reason=live?'Завершите активного босса':playerLevel(data.save)<b.level?'Нужен уровень '+b.level:b.requires&&!c.progress.targets.includes(b.requires)?'Победите предыдущую цель':c.progress.marks<b.entry?'Не хватает знаков':!c.owner?'Операцию начинает глава':'';
 return '<article class="clan-boss-card"><div class="clan-boss-scene" style="--clan-scene:url(assets/district-'+b.map+'.webp)"><img src="assets/boss-'+b.art+'.png" alt="" loading="lazy"></div><div><span class="eyebrow">ОПЕРАЦИЯ · УР. '+b.level+'</span><h3>'+esc(b.name)+'</h3><b>'+fmt(b.hp)+' HP</b><p>Запуск: '+(b.entry?b.entry+' знаков':'бесплатно')+'<br>Победа: +'+b.marks+' знаков клану</p><button class="'+(reason?'secondary':'primary')+'" data-clan-boss="'+b.id+'" '+(reason?'disabled':'')+'>'+(reason?'Недоступно':'Начать операцию')+'</button><small>'+esc(reason||'Общий урон · награда по вкладу')+'</small></div></article>';};
 root.innerHTML='<div class="clan-banner"><span class="eyebrow orange">СИЛА В ЕДИНСТВЕ</span><h2>'+esc(c?.name||'Найди своих')+'</h2><p>До 20 выживших. Общий урон, казна и доска побед.</p></div>'+(c?
 '<div class="clan-bank"><div><span class="eyebrow">КАЗНА ОТРЯДА</span><strong>'+fmt(c.progress.marks)+' <small>знаков</small></strong><p>За победы над клановыми боссами. Тратятся на запуск операций.</p></div><div><b>'+c.progress.wins+'</b><small>общих побед</small></div><button class="secondary" id="clans-refresh">Обновить</button></div>'+c.completed.map(r=>row('Награда готова · '+esc(r.name),'Босс повержен отрядом','<button class="primary" data-raid="'+r.id+'">Забрать награду</button>')).join('')+
 '<div class="section-title"><h3>Операции клана</h3><small>Один клановый босс одновременно</small></div><div class="clan-boss-grid">'+c.bosses.map(bossCard).join('')+'</div><div class="clan-columns"><section class="settings-card"><h3>Доска клана</h3><p>'+ (c.owner?'Выбери до трёх полученных медалей. Они видны в профилях участников.':'Медали, выставленные главой клана.')+'</p><div class="medal-picker">'+c.achievements.filter(m=>c.owner||board.has(m.id)).map(m=>c.owner?'<button class="medal-choice" data-clan-medal="'+m.id+'" aria-pressed="'+board.has(m.id)+'" '+(!m.earned?'disabled':'')+'>'+medalMarkup(m)+'<small>'+fmt(m.progress)+' / '+fmt(m.goal)+'</small></button>':'<article class="medal-choice">'+medalMarkup(m)+'</article>').join('')+'</div>'+ (c.owner?'<button class="secondary" id="clan-board-save">Сохранить доску</button>':!board.size?'<p>Медали пока не выставлены.</p>':'')+'</section><section class="settings-card"><h3>Активные рейды</h3>'+ (c.raids.map(r=>row(esc(r.name||MAPS[r.map].boss),fmt(r.hp)+' / '+fmt(r.maxHp)+' HP','<button class="primary" data-raid="'+r.id+'">К боссу</button>')).join('')||'<p>Запусти клановую операцию или обычного босса на карте.</p>')+'</section></div><div class="clan-columns"><section class="settings-card"><h3>Отряд · '+c.members.length+'/20</h3>'+c.members.map(m=>row(player(m),'Уровень '+m.level)).join('')+'<button class="secondary" data-clan-action="leave">Покинуть клан</button></section>'+ (c.owner?'<section class="settings-card"><h3>Заявки</h3>'+ (c.requests.map(m=>row(player(m),'Уровень '+m.level,'<button class="primary" data-clan-action="accept" data-code="'+m.code+'">Принять</button><button class="secondary" data-clan-action="decline" data-code="'+m.code+'">Отклонить</button>')).join('')||'<p>Новых заявок нет.</p>')+'</section>':'')+'</div>':
 '<div class="clan-columns"><section class="settings-card"><h3>Создать клан</h3><p>Бесплатно со 2 уровня. Принимай заявки и собирай отряд.</p><form id="clan-create" class="friend-form"><input aria-label="Название клана" placeholder="Название клана" minlength="3" maxlength="28" required><button class="primary">Создать</button></form></section><section class="settings-card"><h3>Открытые кланы</h3>'+ (data.clans.map(x=>row(esc(x.name),x.count+'/20 участников','<button class="secondary" data-clan-action="request" data-code="'+x.code+'" '+(x.requested||x.count>=20?'disabled':'')+'>'+ (x.requested?'Заявка отправлена':'Вступить')+'</button>')).join('')||'<p>Стань основателем первого клана.</p>')+'</section></div>');
 const act=async(action,body)=>{try{await api('clans/'+action,body);await clansUI(root,api,toast,openRaid)}catch(e){toast(e.message)}};
 root.querySelectorAll('[data-clan-action]').forEach(b=>b.onclick=()=>{b.disabled=true;act(b.dataset.clanAction,{code:b.dataset.code}).finally(()=>b.disabled=false)});
 root.querySelectorAll('[data-raid]').forEach(b=>b.onclick=()=>openRaid(b.dataset.raid));
 root.querySelectorAll('[data-clan-boss]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const reply=await api('clans/boss',{boss:b.dataset.clanBoss});const r=reply.clan.raids.find(r=>r.clan);if(r)openRaid(r.id)}catch(e){toast(e.message);b.disabled=false}});
 root.querySelectorAll('[data-clan-medal]').forEach(b=>b.onclick=()=>{const id=b.dataset.clanMedal;if(board.has(id))board.delete(id);else if(board.size<3)board.add(id);else{toast('На доске помещаются три медали');return}b.setAttribute('aria-pressed',board.has(id));});
 root.querySelector('#clan-board-save')?.addEventListener('click',()=>act('display',{medals:[...board]}));
 root.querySelector('#clans-refresh')?.addEventListener('click',()=>clansUI(root,api,toast,openRaid));
 bindPlayerProfiles(root,api,toast);
 const form=root.querySelector('form');if(form)form.onsubmit=e=>{e.preventDefault();const b=form.querySelector('button');b.disabled=true;act('create',{name:form.querySelector('input').value}).finally(()=>b.disabled=false)};
 }catch(e){root.innerHTML='<p class="page-intro">'+esc(e.message)+'</p><button class="secondary">Повторить</button>';root.querySelector('button').onclick=()=>clansUI(root,api,toast,openRaid)}
}
