import {socialAction,ensureSocial} from './friends-domain.js';
import {freshSave,restoreEnergy,spendEnergy,RAID_COST,BOSS_COST,MAPS,WEAPONS,stats,unlocked,bossUnlocked,upgradeCost,runXP,raidDamage,ARMOR,armorUnlocked,migrateSave} from './balance.js';
export function createHandler(db,commit,id){
 const err=(text,status=400)=>{throw Object.assign(new Error(text),{status})};
 function daily(s){let date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(s.daily.date!==date)s.daily={date,kills:0,claimed:false};restoreEnergy(s)}
 function viewRaid(r,uid){return {id:r.id,map:r.map,hp:r.hp,maxHp:r.maxHp,created:r.created,owner:r.owner===uid,members:Object.entries(r.members).map(([pid,v])=>({name:db.players[pid].name,damage:v.damage,me:pid===uid,claimed:v.claimed})),nextAttack:r.members[uid]?.nextAttack||0,joined:!!r.members[uid]}}
 return async function handle(req,res,url){
  if(!url.pathname.startsWith('/api/'))return false;
  const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))};
  try{
   if(req.method==='POST'&&req.headers.origin&&req.headers.origin!==url.origin)err('Недопустимый источник запроса',403);
   let session=(req.headers.cookie||'').match(/(?:^|;\s*)obitel_session=([a-f0-9]{32})(?:;|$)/)?.[1];
   if(!session||!db.players[session]){session=id();db.players[session]={name:'Странник '+session.slice(0,4).toUpperCase(),save:freshSave(),ticket:null};res.setHeader('Set-Cookie',`obitel_session=${session}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000`);commit()}
   let p=db.players[session],s=migrateSave(p.save);daily(s);let b={};if(req.method==='POST'){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>4096)err('Слишком большой запрос',413)}try{b=raw?JSON.parse(raw):{}}catch{err('Некорректный JSON')}}
   let result={};const path=url.pathname;
   if(req.method==='GET'&&path==='/api/profile')result={name:p.name};
   else if(path.startsWith('/api/friends'))result=socialAction(db,session,path,req.method,b,id);
   else if(req.method==='POST'&&path==='/api/upgrade'){const f=b.field;if(!['weaponLevel','armor','engine','body','trunk'].includes(f))err('Нет такого улучшения');let price=upgradeCost(s[f]);if(s[f]>=10||s.scrap<price)err('Не хватает деталей');s.scrap-=price;s[f]++}
   else if(req.method==='POST'&&path==='/api/armor'){let i=b.armor;if(!Number.isInteger(i)||!ARMOR[i])err('Нет такой брони');if(!s.ownedArmor.includes(i)){let a=ARMOR[i];if(!armorUnlocked(s,i))err('Нужен уровень '+a.level+' или победы над боссами: '+a.bosses);if(s.scrap<a.cost||s.cloth<a.cloth||s.cores<a.cores)err('Недостаточно материалов');s.scrap-=a.cost;s.cloth-=a.cloth;s.cores-=a.cores;s.ownedArmor.push(i)}s.armorTier=i}
   else if(req.method==='POST'&&path==='/api/weapon'){let i=b.weapon;if(!Number.isInteger(i)||!WEAPONS[i])err('Нет такого оружия');if(!s.owned.includes(i)){if(s.scrap<WEAPONS[i].cost)err('Не хватает деталей');s.scrap-=WEAPONS[i].cost;s.owned.push(i)}s.weapon=i}
   else if(req.method==='POST'&&path==='/api/daily'){if(s.daily.kills<20||s.daily.claimed)err('Награда недоступна');s.scrap+=120;s.cores++;s.daily.claimed=true}
   else if(req.method==='POST'&&path==='/api/run/start'){let m=b.map;if(!Number.isInteger(m)||!MAPS[m]||!unlocked(s,m))err('Район закрыт');if(!spendEnergy(s,RAID_COST))err('Недостаточно энергии');p.ticket={id:id(),map:m,started:Date.now()};result.ticket=p.ticket.id}
   else if(req.method==='POST'&&path==='/api/run/end'){if(p.lastResult?.ticket===b.ticket){send(200,{...p.lastResult.result,save:s,serverTime:Date.now()});return true}let t=p.ticket;if(!t||t.id!==b.ticket)err('Вылазка уже завершена или недействительна',409);let maxKills=27+t.map*3,kills=Math.max(0,Math.min(maxKills,Math.floor(Number(b.kills)||0)));let win=b.win===true&&kills===maxKills&&Date.now()-t.started>18000;let loot=Math.max(0,Math.min(kills*8,Math.floor(Number(b.loot)||0)));let reward=Math.round((win?MAPS[t.map].reward+loot:loot*.35)*stats(s).loot),xp=runXP(kills,win,t.map);s.scrap+=reward;s.cloth+=win?3+t.map:0;s.xp+=xp;s.kills+=kills;s.daily.kills+=kills;if(win)s.districtRuns[t.map]++;p.ticket=null;result={reward,xp,win};p.lastResult={ticket:t.id,result};}
   else if(req.method==='POST'&&path==='/api/raids'){let m=b.map;if(!Number.isInteger(m)||!MAPS[m]||!bossUnlocked(s,m))err('Нужны 3 зачистки и рекомендуемый уровень');let existing=Object.values(db.raids).find(r=>r.owner===session&&r.map===m&&r.hp>0);if(existing){result.raid=viewRaid(existing,session)}else{let rid=id().slice(0,12),hp=750*(1+m*.7);let r={id:rid,map:m,owner:session,hp,maxHp:hp,created:Date.now(),members:{[session]:{damage:0,nextAttack:0,claimed:false}}};db.raids[rid]=r;result.raid=viewRaid(r,session)}}
   else if(/^\/api\/raids\/[a-f0-9]{12}(\/join|\/attack|\/claim)?$/.test(path)){let parts=path.split('/'),r=db.raids[parts[3]];if(!r)err('Рейд не найден',404);let action=parts[4];if(req.method==='POST'&&action==='join'){if(r.hp<=0)err('Босс уже повержен');if(!r.members[session]){if(Object.keys(r.members).length>=10)err('В рейде уже 10 игроков');r.members[session]={damage:0,nextAttack:0,claimed:false}}}else if(req.method==='POST'&&action==='attack'){let member=r.members[session];if(!member)err('Сначала присоединись к рейду');if(!bossUnlocked(s,r.map))err('Нужны 3 зачистки района и рекомендуемый уровень');if(r.hp<=0)err('Босс уже повержен');if(member.nextAttack>Date.now())err('Отряд ещё возвращается');if(!spendEnergy(s,BOSS_COST))err('Недостаточно энергии');let st=stats(s),weapon=WEAPONS[s.weapon],damage=Math.min(r.hp,raidDamage(s));r.hp-=damage;member.damage+=damage;member.nextAttack=Date.now()+45000;result.damage=damage;
   }else if(req.method==='POST'&&action==='claim'){let member=r.members[session];if(!member||!member.damage||member.claimed||r.hp>0)err('Награда недоступна');member.claimed=true;s.scrap+=MAPS[r.map].reward*2;s.cores+=3;s.bossKills++;s.cloth+=6;s.xp+=45;if(!s.cleared.includes(r.map))s.cleared.push(r.map)}else if(req.method!=='GET'||action)err('Метод не поддерживается',405);result.raid=viewRaid(r,session)}
   else err('Метод не найден',404);
   commit();send(200,{...result,save:s,serverTime:Date.now()});
  }catch(e){send(e.status||500,{error:e.status?e.message:'Ошибка сервера'})}return true;
 }
}
