import {inviteVK,inviteLink,launchValue,inVK} from './platform.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function friendsUI(root,api,toast,openRaid){
 let loading=false;
 async function render(){if(loading)return;loading=true;try{const data=await api('friends');root.innerHTML=`<div class="settings-card"><span class="eyebrow orange">СВОИ В ГОРОДЕ</span><h2>Выживать вместе.</h2><p>Добавляй игроков по коду или приглашению. После принятия заявки здесь появится их открытый рейд. Каждый атакует в удобное время — здоровье босса общее.</p><div class="friend-code"><span>ТВОЙ КОД</span><strong>${data.code}</strong><button class="secondary" id="friend-copy">ССЫЛКА ПРИГЛАШЕНИЯ</button>${inVK?'<button class="secondary" id="vk-invite">ПРИГЛАСИТЬ ИЗ ВК</button>':''}</div><form id="friend-form"><label for="friend-code-input">Код друга</label><div class="friend-form"><input id="friend-code-input" maxlength="12" required pattern="[a-fA-F0-9]{12}" autocomplete="off" placeholder="12 символов" value="${escape(launchValue('friend')||'')}"><button class="primary">ДОБАВИТЬ В ДРУЗЬЯ</button></div></form></div><div class="section-title"><h3>Входящие заявки</h3><span>${data.requests.length}</span></div><div class="party-list">${data.requests.map(p=>`<div><b>${escape(p.name)}</b><button class="primary" data-accept="${p.code}">ПРИНЯТЬ</button><button class="secondary" data-decline="${p.code}">ОТКЛОНИТЬ</button></div>`).join('')||'<p class="page-intro">Новых заявок пока нет.</p>'}</div><div class="section-title"><h3>Твой отряд</h3><button class="secondary" id="friends-refresh">ОБНОВИТЬ</button></div><div class="party-list">${data.friends.map(p=>`<div><span><b>${escape(p.name)}</b><small>${p.raid?'Открытый рейд · '+p.raid.hp+' HP':'Готовится к следующей вылазке'}</small></span>${p.raid?`<button class="primary" data-friend-raid="${p.raid.id}">К БОССУ →</button>`:''}</div>`).join('')||'<p class="page-intro">Отправь другу ссылку и прими его заявку. Здесь появится ваш отряд.</p>'}</div>`;
 root.querySelector('#friends-refresh').onclick=render;
 const mutate=async(path,code)=>{try{await api(path,{code});toast(path.endsWith('request')?'Заявка отправлена':'Список друзей обновлён');await render()}catch(e){toast(e.message)}};
 root.querySelector('#friend-form').onsubmit=e=>{e.preventDefault();mutate('friends/request',root.querySelector('input').value.trim().toLowerCase())};
 root.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>mutate('friends/accept',b.dataset.accept));root.querySelectorAll('[data-decline]').forEach(b=>b.onclick=()=>mutate('friends/decline',b.dataset.decline));root.querySelectorAll('[data-friend-raid]').forEach(b=>b.onclick=()=>openRaid(b.dataset.friendRaid));
 root.querySelector('#friend-copy').onclick=async()=>{const link=inviteLink('friend',data.code);try{await navigator.clipboard.writeText(link);toast('Приглашение скопировано')}catch{root.querySelector('input').value=data.code;toast('Передай другу свой код: '+data.code)}};
 if(root.querySelector('#vk-invite'))root.querySelector('#vk-invite').onclick=()=>inviteVK().catch(e=>toast(e.message||'Приглашение закрыто'));
 }catch(e){root.innerHTML='<div class="settings-card"><p>'+escape(e.message)+'</p><button class="secondary" id="friends-retry">ПОВТОРИТЬ</button></div>';root.querySelector('button').onclick=render}finally{loading=false}}
 render();
}
