import {profileEditor,AVATARS} from './profile-ui.js';
let playerProfile={name:'Странник',avatar:0};
function showProfile(data){playerProfile={...playerProfile,...data};const name=document.getElementById('profile-name');if(name)name.textContent=playerProfile.name;const avatar=document.querySelector('.profile .avatar');if(avatar){avatar.textContent=AVATARS[playerProfile.avatar||0];avatar.className='avatar avatar-'+(playerProfile.avatar||0)}}
import {clansUI} from './clans-ui.js';
import {friendsUI} from './friends-ui.js';
import {launchValue,inviteLink} from './platform.js';
import {requestAPI} from './client-api.js';
import {MAPS,WEAPONS,freshSave,playerLevel,stats,upgradeCost,unlocked,enemyStats,restoreEnergy,ENERGY_MAX,ENERGY_INTERVAL,RAID_COST,BOSS_COST,bossUnlocked,levelProgress,sprintStep,ARMOR,armorUnlocked,raidProfile,weaponUnlocked,expeditionRank} from './balance.js';
import {bossPortrait,scene,background,person,car,loadArt,setAppearance,drawItem,drawWeapon,loot} from './art.js';
const $=s=>document.querySelector(s);const key='obitel-save-v1';let save=freshSave();try{const v=JSON.parse(localStorage.getItem(key));if(v?.version===1&&Array.isArray(v.owned)&&Array.isArray(v.cleared))save={...save,...v};}catch{}
let selected=0,page='map',run=null,last=0,toastTimer,keys=new Set(),stick={x:0,y:0};
let raid=null,serverOffset=0,networkReady=false,busy=false,sprintHeld=false;
const prefsKey='obitel-settings-v1';let prefs={particles:true,contrast:false,runToggle:false};try{prefs={...prefs,...JSON.parse(localStorage.getItem(prefsKey)||'{}')}}catch{}document.body.classList.toggle('high-contrast',prefs.contrast);

async function api(path,body){const data=await requestAPI(path,body);if(path==='profile')showProfile({name:data.name,avatar:data.avatar||0});if(data.save){save=data.save;persist()}if(data.serverTime)serverOffset=data.serverTime-Date.now();return data}
async function connect(){const status=$('.connection');status.textContent='ПОДКЛЮЧЕНИЕ…';try{await api('profile');networkReady=true;status.innerHTML='<i></i> СЕРВЕР НА СВЯЗИ';$('#connection-error').hidden=true}catch(e){networkReady=false;status.textContent='НЕТ СВЯЗИ';$('#connection-error').hidden=false;$('#connection-message').textContent=e.message}refresh()}

async function action(fn){if(busy)return;if(!networkReady){toast('Сначала подключись к игровому серверу');return}busy=true;try{await fn()}catch(e){toast(e.message)}finally{busy=false;refresh()}}
function energyHud(){restoreEnergy(save,Date.now()+serverOffset);$('#energy').textContent=save.energy;if(page==='map')$('#deploy').disabled=!networkReady||!unlocked(save,selected)||save.energy<RAID_COST;let left=ENERGY_INTERVAL-(Date.now()+serverOffset-save.energyAt);$('#energy-clock').textContent=save.energy>=ENERGY_MAX?'ЗАПАС ПОЛОН':'+1 через '+Math.max(0,Math.ceil(left/60000))+' мин';}

function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function rollDay(){if(save.daily.date!==today())save.daily={date:today(),kills:0,claimed:false}}
function persist(){try{localStorage.setItem(key,JSON.stringify(save));}catch{toast('Браузер не разрешил сохранить прогресс.')}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200)}
function refresh(){setAppearance(save);rollDay();energyHud();$('#scrap').textContent=save.scrap;$('#cores').textContent=save.cores;$('#level').textContent=`Уровень ${playerLevel(save)}`;let progress=levelProgress(save);$('#xp-fill').style.width=progress.percent+'%';$('#xp-caption').textContent=progress.max?'МАКСИМАЛЬНЫЙ УРОВЕНЬ · 500':Math.floor(progress.current)+' / '+progress.required+' XP';$('#car-level').textContent=`УР. ${save.engine+save.body+save.trunk}`;$('#daily-short').textContent=`Устранить 20 заражённых · ${Math.min(20,save.daily.kills)} / 20`;renderPage();document.querySelectorAll('[data-item]').forEach(c=>drawItem(c,Number(c.dataset.item)));document.querySelectorAll('[data-armor]').forEach(b=>b.onclick=()=>action(()=>api('armor',{armor:Number(b.dataset.armor)})))}
function selectMap(i){selected=i;let m=MAPS[i];$('#map-name').textContent=m.name;$('#map-desc').textContent=m.desc;$('#mission').textContent=m.goal;$('#map-threat').textContent=`УГРОЗА ${['I','II','III','IV','V'][i]}`;$('#deploy').disabled=!networkReady||!unlocked(save,i)||save.energy<RAID_COST;$('#deploy-hint').textContent=!unlocked(save,i)?'ПОБЕДИ БОССА ПРЕДЫДУЩЕГО РАЙОНА':save.energy<RAID_COST?'НЕДОСТАТОЧНО ЭНЕРГИИ · +1 КАЖДЫЕ 5 МИНУТ':`ЗАЧИСТОК: ${save.districtRuns[i]} / 3 ДО БОССА`;$('#boss-open').disabled=!bossUnlocked(save,i);$('#boss-progress').textContent=bossUnlocked(save,i)?'БОСС ДОСТУПЕН':`НУЖНО 3 ЗАЧИСТКИ И УРОВЕНЬ ${MAPS[i].level}`;scene($('#scene'),i);document.querySelectorAll('.map-card').forEach((el,j)=>el.classList.toggle('selected',i===j))}
function mapCards(){$('#maps').innerHTML=MAPS.map((m,i)=>`<button class="map-card ${i===selected?'selected':''}" data-map="${i}" aria-label="${m.name}, ${unlocked(save,i)?'доступно':'закрыто'}"><canvas width="260" height="140"></canvas><span class="number">0${i+1}</span><div class="map-info"><b>${m.name}</b><small>ЗАЧИСТКИ ${save.districtRuns[i]} / 3<span class="status">${save.cleared.includes(i)?'✓':unlocked(save,i)?'→':'ЗАКРЫТО'}</span></small></div></button>`).join('');document.querySelectorAll('.map-card').forEach((el,i)=>{scene(el.querySelector('canvas'),i);el.onclick=()=>selectMap(i)})}
const weaponIcon=i=>'<svg viewBox="0 0 180 70" aria-hidden="true">'+(i===0?'<path d="M30 18h112v15H79l-9 30H44l8-29H30z"/><path d="M47 18v-6h83v6M92 35v12H75" fill="none"/><path d="M116 20h12v10h-12" fill="#dfb270"/>':i===1?'<path d="M8 30l34-8h68l13 7h41v9h-46l-8 10H86l-9-9H42L8 46z"/><path d="M81 45l5 22h18l-8-22M51 42l-5 16h14l8-16"/><path d="M65 15h36v8H65zM151 24v15"/><path d="M108 28h29v10h-29" fill="#7e9674"/>':'<path d="M9 39l41-12h41l13-7h63v10h-66l-8 14H58L17 60z" fill="#ab7d4f"/><path d="M55 28h111v11H96l-6 8H61z"/><path d="M105 34h38v13h-38" fill="#bf945f"/>')+'</svg>';
const item=(icon,title,badge,desc,action)=>`<article class="item"><div class="item-icon">${icon}</div><span class="badge">${badge}</span><h3>${title}</h3><p>${desc}</p>${action}</article>`;
const upgrade=(field,name,desc)=>item(field==='engine'?'⚙':field==='trunk'?'▤':'◇',name,`УРОВЕНЬ ${save[field]} / 10`,desc,`<button class="primary" data-upgrade="${field}" ${save[field]>=10||save.scrap<upgradeCost(save[field])?'disabled':''}>${save[field]>=10?'МАКСИМУМ':`УЛУЧШИТЬ · ${upgradeCost(save[field])} ДЕТ.`}</button>`);
const itemArt=i=>'<canvas class="loot-art" data-item="'+i+'" width="180" height="180"></canvas>';
function renderInventory(){return '<div class="section-title"><h3>Склад убежища</h3><span>МАТЕРИАЛЫ И БРОНЯ</span></div><div class="supply-grid">'+[[0,'Детали',save.scrap,'Оружие, машина и мастерская'],[1,'Ядра',save.cores,'Рейд-боссы и ежедневные контракты'],[2,'Ткань',save.cloth||0,'3–10 за зачистку · 6 за босса']].map(([i,n,v,d])=>'<article class="supply">'+itemArt(i)+'<div><small>'+n+'</small><strong>'+v+'</strong><p>'+d+'</p></div></article>').join('')+'</div><div class="section-title"><h3>Защита выжившего</h3><span>ПОБЕДЫ НАД БОССАМИ: '+(save.bossKills||0)+'</span></div><div class="armor-grid">'+ARMOR.map((a,i)=>{const owned=(save.ownedArmor||[0]).includes(i),active=(save.armorTier||0)===i,open=armorUnlocked(save,i),afford=save.scrap>=a.cost&&(save.cloth||0)>=a.cloth&&save.cores>=a.cores;return '<article class="armor-card '+(active?'equipped':'')+'">'+itemArt(a.icon)+'<span class="badge">'+(active?'ЭКИПИРОВАНО':owned?'В ИНВЕНТАРЕ':open?'ЧЕРТЁЖ ОТКРЫТ':'ЗАКРЫТО')+'</span><h3>'+a.name+'</h3><strong class="armor-stat">+'+a.hp+' HP</strong><p>'+a.description+'</p><small>'+(!owned?'Уровень '+a.level+(a.bosses?' или '+a.bosses+' побед над боссами':''):'Комплект сохранён навсегда')+'</small>'+(!owned?'<div class="recipe">'+(a.votes?'Цена: '+a.votes+' голосов':a.cost+' деталей · '+a.cloth+' ткани'+(a.cores?' · '+a.cores+' ядер':''))+'</div>':'')+'<button class="'+(active?'secondary':'primary')+'" data-armor="'+i+'" '+(active||!owned&&(a.votes||!open||!afford)?'disabled':'')+'>'+(active?'НАДЕТО':owned?'НАДЕТЬ':a.votes?a.votes+' ГОЛОСОВ · СКОРО':open?'СОЗДАТЬ':'НУЖЕН ОПЫТ')+'</button></article>'}).join('')+'</div>'}
function renderWeapons(){const boost=(1+save.weaponLevel*.08)*(1+save.engine*.04);return '<div class="section-title"><h3>Арсенал убежища</h3><span>10 МОДЕЛЕЙ · МАСТЕРСКАЯ</span></div><div class="weapon-grid">'+WEAPONS.map((w,i)=>{const owned=save.owned.includes(i),equipped=save.weapon===i,dps=w.damage*(w.pellets||1)/w.rate*boost;return '<article class="weapon-card '+(equipped?'equipped':'')+'"><div class="weapon-stage"><span class="weapon-number">0'+(i+1)+'</span><span class="weapon-type">'+(w.votes?'КОЛЛЕКЦИЯ ЗА ГОЛОСА':w.pellets?'ДРОБОВИК':'ОГНЕСТРЕЛЬНОЕ')+'</span><canvas data-weapon-art="'+i+'" width="440" height="440"></canvas><span class="weapon-state">'+(equipped?'● В РУКАХ':owned?'В ИНВЕНТАРЕ':'ЧЕРТЁЖ')+'</span></div><div class="weapon-info"><h3>'+w.name+'</h3><p>'+w.description+' Уровень '+(w.level||1)+'.</p><div class="weapon-stats"><div><small>УРОН</small><b>'+Math.round(w.damage*boost)+(w.pellets?' × '+w.pellets:'')+'</b></div><div><small>ПЕРЕЗАРЯДКА</small><b>'+w.rate+' с</b></div><div><small>ДАЛЬНОСТЬ</small><b>'+w.range+'</b></div></div><div class="power-label"><span>УРОН В СЕКУНДУ</span><strong>'+Math.round(dps)+'</strong></div><div class="weapon-power"><i style="width:'+Math.min(100,dps/200*100)+'%"></i></div><small class="weapon-note">'+(w.pellets?'Показатель при попадании всех дробин.':'С учётом мастерской и генератора.')+'</small><button class="'+(equipped?'secondary':'primary')+'" data-weapon="'+i+'" '+(equipped||!weaponUnlocked(save,i)||!owned&&(w.votes||save.scrap<w.cost)?'disabled':'')+'>'+(equipped?'ЭКИПИРОВАНО':owned?'ВЗЯТЬ В РУКИ':w.votes?w.votes+' ГОЛОСОВ · СКОРО':!weaponUnlocked(save,i)?'УРОВЕНЬ '+w.level:'СОЗДАТЬ · '+w.cost+' ДЕТАЛЕЙ')+'</button></div></article>'}).join('')+'</div>'}
function renderPage(){if(page==='clans')clansUI($('#clans-page'),api,toast,async id=>{try{raid=(await api('raids/'+id)).raid;navigate('raids')}catch(e){toast(e.message)}});if(page==='friends')friendsUI($('#friends-page'),api,toast,async id=>{try{raid=(await api('raids/'+id)).raid;navigate('raids')}catch(e){toast(e.message)}});if(page==='map'){mapCards();selectMap(selected)}if(page==='gear'){$('#gear-page').innerHTML=`<div class="loadout-hero"><canvas id="loadout-avatar" width="400" height="380"></canvas><div><span class="eyebrow orange">ТВОЙ ВЫЖИВШИЙ</span><h2>${ARMOR[save.armorTier||0].name}</h2><p>${ARMOR[save.armorTier||0].description}</p><strong>${WEAPONS[save.weapon].name}</strong><div class="stat-pills"><span>${stats(save).hp} HP</span><span>${Math.round(stats(save).damage)} УРОН</span><span>${playerLevel(save)} УРОВЕНЬ</span></div></div></div><p class="page-intro">Каждое оружие меняет дистанцию боя. Уровни 1–500. Каждые 25 уровней растут сложность вылазок и награда опытом. Патроны не ограничены; стрельба автоматическая. Улучшения мастерской действуют на всё оружие.</p>${renderWeapons()}<div class="item-grid">${upgrade('weaponLevel','Верстак оружейника',`+8% базового урона за уровень. Сейчас +${save.weaponLevel*8}%.`)}${upgrade('armor','Усиление подкладки',`+8 здоровья за уровень. Сейчас +${save.armor*8} HP. Работает с любым комплектом.`)}${item('✚','Полевой комплект','АВТОМАТИЧЕСКОЕ ЛЕЧЕНИЕ','Аптечки выпадают в бою. Подойди, чтобы восстановить 28 здоровья.','')}</div>`+renderInventory()}
if(page==='gear'){document.querySelectorAll('[data-item]').forEach(c=>drawItem(c,Number(c.dataset.item)));document.querySelectorAll('[data-armor]').forEach(b=>b.onclick=()=>action(()=>api('armor',{armor:Number(b.dataset.armor)})))}
if(page==='garage'){$('#garage-page').innerHTML=`<p class="page-intro">«Кочевник» — твоя мобильная база. Двигатель питает оружейный модуль, бронекорпус усиливает защиту, багажник вмещает больше добычи.</p><canvas class="wide-art" width="960" height="320"></canvas><div class="item-grid">${upgrade('engine','Генератор',`+4% урона за уровень. Сейчас +${save.engine*4}%.`)}${upgrade('body','Бронекорпус',`+4% здоровья за уровень. Сейчас +${save.body*4}%.`)}${upgrade('trunk','Грузовой отсек',`+5% деталей за вылазку за уровень. Сейчас +${save.trunk*5}%.`)}</div>`;let c=$('#garage-page canvas');scene(c,0,-1)}
if(page==='daily'){$('#daily-page').innerHTML=`<p class="page-intro">Одна понятная цель на день. Контракт обновляется в 00:00 по Москве. Пропущенный день не отнимает прогресс. В прототипе время и награды контролирует локальный сервер.</p><div class="item-grid">${item('▤','Город должен стать тише',`СЕГОДНЯ · ${Math.min(save.daily.kills,20)} / 20`,`Устрани 20 заражённых в любых районах. Награда: 120 деталей и 1 ядро.`, `<button class="primary" id="claim" ${save.daily.claimed||save.daily.kills<20?'disabled':''}>${save.daily.claimed?'НАГРАДА ПОЛУЧЕНА':save.daily.kills<20?'КОНТРАКТ В ПРОЦЕССЕ':'ЗАБРАТЬ НАГРАДУ'}</button>`)}${item('◇','Трофеи заражённой зоны',`${save.cores} ЯДЕР`,`Ядро выдаётся за победу над боссом. В этой версии это коллекционный ресурс; рецепты редкой экипировки запланированы.`, '')}</div>`}
if(page==='raids')renderRaids();if(page==='settings')renderSettings();
if(page==='guide')$('#guide-page').innerHTML=`<div class="journal"><h3>Твой первый выход</h3><p>Выбери район и начни вылазку. Перемещайся WASD или стрелками; на телефоне используй левый джойстик. Оружие само стреляет в ближайшего врага в радиусе. Удерживай Shift, пробел или кнопку «Бежать»: скорость выше на 65%, расходуется выносливость. Бег не даёт неуязвимость. После истощения восстанови 30%.</p><h3>Никогда не стой на месте</h3><p>Ходоки медленнее, бегуны быстрее, громилы живучее. Зачистка стоит 8 энергии и завершается после трёх волн. После волны отряд продвигается на следующий участок улицы. Босс сам не появляется. Аптечки и детали нужно подбирать.</p><h3>Вернись сильнее</h3><p>Зачистки приносят детали и опыт. После трёх зачисток и достижения рекомендуемого уровня откроется рейд-босс. Создай рейд, поделись ссылкой, атакуйте в разное время: здоровье общее. Атака стоит 12 энергии. После победы забери награду — это откроет следующий район. При отступлении сохраняется 35% подобранных деталей.</p><h3>О прототипе</h3><p>Пять районов с детальными фонами, пиксельные персонажи, три оружия, броня, машина, энергия, контракты и асинхронные рейды. Прогресс хранится на локальном сервере. Есть гостевые профили и ссылки на рейд. Вход и друзья ВК, интернет-размещение, реклама и платежи ещё не подключены. Анимация персонажей пока ограничена.</p></div>`;
document.querySelectorAll('[data-weapon-art]').forEach(c=>drawWeapon(c,Number(c.dataset.weaponArt)));if($('#loadout-avatar')){let c=$('#loadout-avatar');person(c.getContext('2d'),180,355,'hero',3,0,1,0,false)}document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>action(async()=>{await api('upgrade',{field:b.dataset.upgrade});toast('Улучшение установлено')}));document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>action(()=>api('weapon',{weapon:+b.dataset.weapon})));if($('#claim'))$('#claim').onclick=()=>action(async()=>{await api('daily',{});toast('Контракт закрыт: +120 деталей, +1 ядро')})}
function navigate(p){page=p;document.querySelectorAll('.page').forEach(el=>el.hidden=el.id!==`${p}-page`);document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#page-title').textContent={map:'Город больше не спит.',gear:'Снаряжение решает.',garage:'Дом на четырёх колёсах.',daily:'Каждый день — новая цель.',guide:'Знание сохраняет жизнь.',raids:'Один босс. Общая цель.',friends:'Свои не бросают.',clans:'Выживаем вместе.',settings:'Настрой свой ритм.'}[p];renderPage()}
const menuIcons={"map":"M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2z M9 3v16 M15 5v16","gear":"M4 14l3-3 3 3 8-8 2 2-8 8 2 3-3 2-3-3-3 1-2-2z","garage":"M4 15V9l3-5h10l3 5v6 M3 10h18v7H3z M6 17v3 M18 17v3 M6 13h2 M16 13h2","daily":"M7 4H4v17h16V4h-3 M8 2h8v5H8z M8 11h8 M8 15h6","raids":"M12 2l8 4v6c0 5-8 10-8 10S4 17 4 12V6z M9 9l6 6 M15 9l-6 6","guide":"M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3z M12 6v15","settings":"M9 3h6l1 4 4 1v8l-4 1-1 4H9l-1-4-4-1V8l4-1z M15 12a3 3 0 1 0-6 0 3 3 0 0 0 6 0"};document.querySelectorAll('nav [data-page]').forEach(b=>b.querySelector('span').innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="'+(menuIcons[b.dataset.page]||'M4 20v-6h16v6 M8 14V8h8v6 M12 2v6')+'"/></svg>');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('.brand').onclick=e=>{e.preventDefault();navigate('map')};$('#deploy').onclick=()=>action(()=>start());$('#boss-open').onclick=()=>navigate('raids');
const canvas=$('#battle'),display=canvas.getContext('2d'),world=document.createElement('canvas');world.width=960;world.height=600;const g=world.getContext('2d');const bg=document.createElement('canvas');bg.width=960;bg.height=600;
async function start(){if(!unlocked(save,selected))return;let data=await api('run/start',{map:selected});let st=stats(save);run={ticket:data.ticket,rank:expeditionRank(save),map:selected,hp:st.hp,maxHp:st.hp,x:430,y:410,face:1,time:0,wave:0,enemies:[],shots:[],drops:[],particles:[],kills:0,loot:0,shotCd:.2,stamina:100,exhausted:false,running:false,anim:0,moving:false,travel:0,transition:null,invulnerable:0,paused:false,ended:false,next:1,boss:false,damage:st.damage,speed:st.speed,lootMult:st.loot};background(bg.getContext('2d'),selected);sprintHeld=false;keys.clear();setSprint(false);stick={x:0,y:0};document.body.classList.add('in-battle');$('#game').hidden=false;$('#overlay').hidden=true;$('#boss-hud').hidden=true;$('#battle-location').textContent=MAPS[selected].name.toUpperCase();$('#wave-label').textContent='ПЕРИМЕТР · ГОТОВЬСЯ';canvas.focus();updateHud()}
function spawnWave(){let r=run;r.wave++;if(r.wave<=3){let n=5+r.wave*2+r.map;for(let i=0;i<n;i++){let type=i%5===4?'tank':i%3===2?'runner':'walker';spawn(type,i)}$('#wave-label').textContent=`ВОЛНА ${r.wave} / 3`}else{finish(true)}}
function spawn(type,i){let r=run,side=i%4;let x=side===0?30:side===1?930:100+Math.random()*760,y=side===2?260:side===3?540:285+Math.random()*220;let st=enemyStats(r.map,Math.min(r.wave,3),type,r.rank);r.enemies.push({x,y,type,...st,maxHp:st.hp,cd:1.8,flash:0,attack:null})}
function setSprint(value){sprintHeld=value;$('#dash').classList.toggle('running',value)}
function advanceSection(dt){let r=run,tr=r.transition;tr.elapsed+=dt;let f=Math.min(1,tr.elapsed/2.4),smooth=f*f*(3-2*f);r.travel=tr.start+960*smooth;r.x=tr.x+(190-tr.x)*smooth;r.anim+=dt*1.8;r.moving=true;r.running=true;if(f===1){r.transition=null;r.moving=false;r.running=false;spawnWave()}updateHud()}
function beginSection(){let r=run;for(let d of r.drops)if(d.kind==='scrap')r.loot+=d.amount;r.drops=[];r.shots=[];r.next=1.8;r.face=1;r.transition={elapsed:0,start:r.travel,x:r.x};$('#wave-label').textContent='ПУТЬ СВОБОДЕН · ДВИЖЕМСЯ ДАЛЬШЕ';}
function movement(){return[(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stick.x,(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+stick.y]}
addEventListener('keydown',e=>{if($('#game').hidden)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(['ShiftLeft','ShiftRight','Space'].includes(e.code)&&!e.repeat){setSprint(prefs.runToggle?!sprintHeld:true)}if(e.code==='Escape')pause()});addEventListener('keyup',e=>{keys.delete(e.code);if(['ShiftLeft','ShiftRight','Space'].includes(e.code)&&!prefs.runToggle)setSprint(false)});addEventListener('blur',()=>{keys.clear();setSprint(false);stick={x:0,y:0};if(run&&!run.ended&&!run.paused)pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&run&&!run.ended&&!run.paused)pause()});$('#dash').onpointerdown=e=>{e.preventDefault();$('#dash').setPointerCapture(e.pointerId);setSprint(prefs.runToggle?!sprintHeld:true)};$('#dash').onpointerup=$('#dash').onpointercancel=$('#dash').onlostpointercapture=()=>{if(!prefs.runToggle)setSprint(false)};$('#pause').onclick=pause;
let pointer=null;const joy=$('#joystick');function joystick(e){if(e.pointerId!==pointer)return;let b=joy.getBoundingClientRect(),x=(e.clientX-b.left-b.width/2)/40,y=(e.clientY-b.top-b.height/2)/40,l=Math.max(1,Math.hypot(x,y));stick={x:x/l,y:y/l};joy.firstElementChild.style.transform=`translate(${stick.x*30}px,${stick.y*30}px)`}joy.onpointerdown=e=>{pointer=e.pointerId;joy.setPointerCapture(pointer);joystick(e)};joy.onpointermove=joystick;joy.onpointerup=joy.onpointercancel=joy.onlostpointercapture=()=>{pointer=null;stick={x:0,y:0};joy.firstElementChild.style.transform=''};
function pause(){if(!run||run.ended)return;run.paused=!run.paused;keys.clear();setSprint(false);stick={x:0,y:0};$('#overlay').hidden=!run.paused;if(run.paused){$('#result-tag').textContent='СВЯЗЬ С УБЕЖИЩЕМ';$('#result-title').textContent='Передышка';$('#result-text').textContent='Вылазка приостановлена.\nОтступление сохранит 35% подобранных деталей.';$('#result-actions').innerHTML='<button class="primary" id="resume">ПРОДОЛЖИТЬ</button><button class="secondary" id="retreat">ОТСТУПИТЬ</button>';$('#resume').onclick=pause;$('#retreat').onclick=()=>finish(false)}}
function burst(x,y,color,n=5){if(!prefs.particles)return;for(let i=0;i<n;i++)run.particles.push({x,y:y-20,vx:(Math.random()-.5)*130,vy:(Math.random()-.5)*100,life:.4,color})}
function update(dt){let r=run;if(!r||r.paused||r.ended)return;r.time+=dt;if(r.transition){advanceSection(dt);return}r.invulnerable=Math.max(0,r.invulnerable-dt);let [dx,dy]=movement(),len=Math.max(1,Math.hypot(dx,dy));r.moving=Math.hypot(dx,dy)>.05;let sprint=sprintStep(r.stamina,r.exhausted,sprintHeld,r.moving,dt);Object.assign(r,sprint);r.anim+=r.moving?dt*(r.running?1.75:1):0;r.x=Math.max(25,Math.min(935,r.x+dx/len*r.speed*sprint.multiplier*dt));r.y=Math.max(275,Math.min(535,r.y+dy/len*r.speed*.8*sprint.multiplier*dt));if(dx)r.face=dx>0?1:-1;
if(!r.enemies.length){r.next-=dt;if(r.next<=0){if(r.wave>=3){finish(true);return}if(r.wave>0){beginSection();return}spawnWave();r.next=1.8}}
let weapon=WEAPONS[save.weapon];r.shotCd-=dt;let target=r.enemies.filter(e=>Math.hypot(e.x-r.x,e.y-r.y)<weapon.range).sort((a,b)=>Math.hypot(a.x-r.x,a.y-r.y)-Math.hypot(b.x-r.x,b.y-r.y))[0];if(target&&r.shotCd<=0){r.face=target.x>r.x?1:-1;let angle=Math.atan2(target.y-r.y,target.x-r.x);for(let j=0;j<(weapon.pellets||1);j++){let a=angle+(j-((weapon.pellets||1)-1)/2)*.115;r.shots.push({x:r.x+r.face*14,y:r.y-55,vx:Math.cos(a)*620,vy:Math.sin(a)*620,life:weapon.range/620,damage:r.damage})}r.shotCd=weapon.rate;burst(r.x+r.face*26,r.y-2,'#ffe1a0',3)}
for(let e of r.enemies){e.cd-=dt;e.flash=Math.max(0,e.flash-dt);let dist=Math.hypot(e.x-r.x,e.y-r.y)||1;if(e.type==='boss'&&e.cd<=0&&!e.attack){e.attack={x:r.x,y:r.y,t:1.1,radius:55+r.map*5};e.cd=4.8-r.map*.3}if(e.attack){e.attack.t-=dt;if(e.attack.t<=0){if(Math.hypot(e.attack.x-r.x,e.attack.y-r.y)<e.attack.radius&&r.invulnerable<=0){r.hp-=e.damage*1.6;r.invulnerable=.65}burst(e.attack.x,e.attack.y,'#d2a270',18);if(r.map===3)e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.03);if(r.map===4&&r.enemies.length<9)spawn('runner',Math.floor(r.time));e.attack=null}}else if(dist>22){e.x+=(r.x-e.x)/dist*e.speed*dt;e.y+=(r.y-e.y)/dist*e.speed*.8*dt}if(dist<25&&r.invulnerable<=0){r.hp-=e.damage;r.invulnerable=.65;burst(r.x,r.y,'#cf9b71',6)}}
for(let s of r.shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(let e of r.enemies){if(e.hp<=0)continue;if(Math.hypot(e.x-s.x,e.y-55-s.y)<(e.type==='boss'?29:18)){e.hp-=s.damage;e.flash=.1;s.life=0;burst(e.x,e.y,'#c6c2a1',3);break}}}r.shots=r.shots.filter(s=>s.life>0);
let dead=r.enemies.filter(e=>e.hp<=0);for(let e of dead){r.kills++;r.drops.push({x:e.x,y:e.y,kind:'scrap',amount:4+Math.floor(Math.random()*5)});if(Math.random()<.2)r.drops.push({x:e.x+14,y:e.y+8,kind:'health'});burst(e.x,e.y,'#657554',8)}r.enemies=r.enemies.filter(e=>e.hp>0);
for(let d of r.drops){if(Math.hypot(d.x-r.x,d.y-r.y)<33){if(d.kind==='health')r.hp=Math.min(r.maxHp,r.hp+28);else r.loot+=d.amount;d.taken=true}}r.drops=r.drops.filter(d=>!d.taken);for(let p of r.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}r.particles=r.particles.filter(p=>p.life>0);if(r.hp<=0)finish(false);updateHud()}
function updateHud(){let r=run;$('#hp-label').textContent=`${Math.max(0,Math.ceil(r.hp))} / ${r.maxHp}`;$('#hp-bar').style.width=`${Math.max(0,r.hp/r.maxHp*100)}%`;$('#kill-label').textContent=`${r.kills} УСТРАНЕНО · ${r.loot} ДЕТ.`;$('#dash').innerHTML=(r.exhausted?'ОТДЫХ':r.running?'БЕГ':'БЕЖАТЬ')+'<small>'+Math.ceil(r.stamina)+'%</small>';$('#dash').disabled=false;$('#stamina-fill').style.width=r.stamina+'%';$('#section-count').textContent='УЧАСТОК '+Math.max(1,r.wave)+' / 3';let boss=r.enemies.find(e=>e.type==='boss');$('#boss-hud').hidden=!boss;if(boss)$('#boss-bar').style.width=`${Math.max(0,boss.hp/boss.maxHp*100)}%`}
function draw(){if(!run||$('#game').hidden)return;let r=run;const offset=r.travel%960,section=Math.floor(r.travel/960);for(let tile=0;tile<2;tile++){let tx=tile*960-offset;g.save();g.translate(tx,0);if((section+tile)%2){g.translate(960,0);g.scale(-1,1)}g.drawImage(bg,0,0);g.restore();}if(r.transition){g.fillStyle='#14201490';g.fillRect(300,200,360,42);g.fillStyle='#edbd7c';g.font='17px monospace';g.textAlign='center';g.fillText('УЧАСТОК ЗАЧИЩЕН →',480,227);g.textAlign='left';}for(let e of r.enemies){if(e.attack){g.fillStyle='#c8764240';g.strokeStyle='#ebaa68';g.lineWidth=2;g.beginPath();g.ellipse(e.attack.x,e.attack.y,e.attack.radius,e.attack.radius*.6,0,0,Math.PI*2);g.fill();g.stroke();g.fillStyle='#e7ba8a';g.font='11px monospace';g.fillText('УХОДИ!',e.attack.x-20,e.attack.y+4)}}for(let d of r.drops)loot(g,d.x,d.y,d.kind,r.time,d.amount||0);let actors=[...r.enemies,{x:r.x,y:r.y,type:'hero'}].sort((a,b)=>a.y-b.y);for(let e of actors){let hero=e.type==='hero',scale=e.type==='boss'?2:1.15;if(hero&&r.invulnerable>0&&Math.floor(r.time*20)%2)continue;person(g,e.x,e.y,e.type,scale,hero?r.anim:r.time,hero?r.face:e.x>r.x?-1:1,e.flash,hero?r.moving:true,hero?r.running:e.type==='runner');if(!hero&&e.hp<e.maxHp){g.fillStyle='#334332';g.fillRect(e.x-16,e.y-70*scale,32,3);g.fillStyle='#bec592';g.fillRect(e.x-16,e.y-70*scale,32*e.hp/e.maxHp,3)}}for(let s of r.shots){g.fillStyle='#ffdda1';g.fillRect(s.x,s.y,7,3)}for(let p of r.particles){g.globalAlpha=p.life/.4;g.fillStyle=p.color;g.fillRect(p.x,p.y,3,3)}g.globalAlpha=1;}
async function finish(win){let r=run;if(r.ended)return;r.ended=true;r.paused=false;if(win)r.loot+=r.drops.filter(d=>d.kind==='scrap').reduce((a,d)=>a+d.amount,0);$('#overlay').hidden=false;$('#result-tag').textContent='СВЯЗЬ С УБЕЖИЩЕМ';$('#result-title').textContent='Возвращение…';$('#result-text').textContent='Сохраняем результат вылазки на сервере.';$('#result-actions').innerHTML='';
const submit=async()=>{try{let result=await api('run/end',{ticket:r.ticket,win,kills:r.kills,loot:r.loot});$('#result-tag').textContent=result.win?'ПРИПАСЫ ДОСТАВЛЕНЫ':'ОТРЯД ЭВАКУИРОВАН';$('#result-title').textContent=result.win?'Район зачищен.':'Ты вернулся живым.';$('#result-text').textContent=(result.win?'Зачисток района: '+save.districtRuns[r.map]+' / 3. Босс ждёт в отдельном рейде.':'Сохранено 35% подобранных деталей.')+'\n+'+result.reward+' деталей · +'+result.xp+' опыта';$('#result-actions').innerHTML='<button class="primary" id="return">В УБЕЖИЩЕ →</button>';$('#return').onclick=()=>{$('#game').hidden=true;$('#overlay').hidden=true;document.body.classList.remove('in-battle');run=null;refresh()}}catch(e){$('#result-title').textContent='Нет связи';$('#result-text').textContent=e.message;$('#result-actions').innerHTML='<button class="primary" id="retry-save">ПОВТОРИТЬ СОХРАНЕНИЕ</button>';$('#retry-save').onclick=submit}};await submit();}
function frame(t){let dt=Math.min((t-last)/1000,.035);last=t;update(dt);if(run&&!$('#game').hidden){draw();let ratio=canvas.clientWidth/Math.max(1,canvas.clientHeight),vw=Math.min(960,Math.max(240,Math.round(600*ratio)));let portrait=vw<960;let vh=Math.min(600,Math.round(vw/ratio));if(canvas.width!==vw||canvas.height!==vh){canvas.width=vw;canvas.height=vh}let left=portrait?Math.max(0,Math.min(960-vw,run.x-vw/2)):0;display.imageSmoothingEnabled=false;let top=Math.max(0,Math.min(600-vh,run.y-vh/2));if(canvas.height!==vh)canvas.height=vh;display.drawImage(world,left,top,vw,vh,0,0,vw,vh)}requestAnimationFrame(frame)}
async function pollRaid(){try{raid=(await api('raids/'+raid.id)).raid;if(page==='raids')renderRaids()}catch{}}
function renderRaids(){let root=$('#raids-page');let m=raid?raid.map:selected;let available=bossUnlocked(save,m);let mine=raid?.members.find(p=>p.me);let cooldown=raid?Math.max(0,Math.ceil((raid.nextAttack-Date.now()-serverOffset)/1000)):0;
root.innerHTML='<p class="page-intro">Друзья атакуют в удобное время. Здоровье босса общее и сохраняется на сервере. Сначала зачисти район трижды, затем собери отряд по ссылке.</p>'+(!raid?'<div class="raid-intro"><canvas width="960" height="420"></canvas><div><span class="eyebrow orange">БОСС РАЙОНА · '+MAPS[m].name+'</span><h2>'+MAPS[m].boss+'</h2><p>Доступ: 3 зачистки и уровень '+MAPS[m].level+'.<br>Сейчас зачисток: '+save.districtRuns[m]+' / 3.</p><button class="primary" id="create-raid" '+(!available?'disabled':'')+'>СОЗДАТЬ РЕЙД</button></div></div>':'<div class="raid-intro"><canvas width="960" height="420"></canvas><div><span class="eyebrow orange">АСИНХРОННЫЙ РЕЙД · '+raid.id+'</span><h2>'+MAPS[m].boss+'</h2><div class="raid-health"><i style="width:'+raid.hp/raid.maxHp*100+'%"></i></div><p>'+raid.hp+' / '+raid.maxHp+' HP · '+raid.members.length+' / 10 участников</p><button class="primary" id="raid-attack" '+(!raid.joined||!available||raid.hp<=0||cooldown||save.energy<BOSS_COST?'disabled':'')+'>'+(raid.hp<=0?'БОСС ПОВЕРЖЕН':cooldown?'ВОЗВРАЩЕНИЕ · '+cooldown+' СЕК':'АТАКОВАТЬ · 12 ЭНЕРГИИ')+'</button><small>Урон рассчитывается по экипировке. Повторная атака через 45 секунд.</small></div></div><div class="raid-controls">'+(!raid.joined&&raid.hp>0?'<button class="primary" id="join-raid">ПРИСОЕДИНИТЬСЯ</button>':'')+'<button class="secondary" id="copy-raid">СКОПИРОВАТЬ ССЫЛКУ ДЛЯ ДРУЗЕЙ</button>'+(raid.hp===0&&mine?.damage&&!mine.claimed?'<button class="primary" id="raid-claim">ЗАБРАТЬ НАГРАДУ · '+MAPS[m].reward*2+' ДЕТ. + 3 ЯДРА</button>':'')+'<button class="secondary" id="close-raid">ДРУГОЙ РЕЙД</button></div><div class="party-list">'+raid.members.map(p=>'<div><span>'+String(p.name).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))+(p.me?' · ТЫ':'')+'</span><b>'+p.damage+' урона</b><small>'+(p.claimed?'Награда получена':'')+'</small></div>').join('')+'</div>')+'<div class="network-note">Бета · гостевой профиль привязан к этому браузеру. Приглашай друзей по ссылке: здоровье босса общее. Вход и список друзей ВК подключаются отдельно.</div>';
const trait=document.createElement('p');trait.className='page-intro';trait.textContent=raidProfile(m).trait;root.prepend(trait);let c=root.querySelector('canvas');scene(c,m,-1);let cg=c.getContext('2d');bossPortrait(cg,m);if($('#create-raid'))$('#create-raid').onclick=()=>action(async()=>{raid=(await api('raids',{map:selected})).raid});if($('#raid-attack'))$('#raid-attack').onclick=()=>action(async()=>{let result=await api('raids/'+raid.id+'/attack',{});raid=result.raid;toast('Отряд нанёс '+result.damage+' урона. Общее здоровье обновлено.')});if($('#join-raid'))$('#join-raid').onclick=()=>action(async()=>{raid=(await api('raids/'+raid.id+'/join',{})).raid});if($('#raid-claim'))$('#raid-claim').onclick=()=>action(async()=>{raid=(await api('raids/'+raid.id+'/claim',{})).raid;toast('Награда получена. Следующий район открыт.')});if($('#close-raid'))$('#close-raid').onclick=()=>{raid=null;renderRaids()};if($('#copy-raid'))$('#copy-raid').onclick=async()=>{const link=inviteLink('raid',raid.id);try{await navigator.clipboard.writeText(link);toast('Ссылка скопирована')}catch{let input=document.createElement('input');input.value=link;input.readOnly=true;root.append(input);input.select()}};
}


function renderSettings(){const el=$('#settings-page');el.innerHTML='<div class="settings-layout"><div class="settings-card"><span class="eyebrow orange">УПРАВЛЕНИЕ И ЭКРАН</span><h2>Под тебя.</h2><p>Настройки сохраняются на этом устройстве.</p>'+[['runToggle','Бег по нажатию','Включить бег одним нажатием вместо удержания.'],['particles','Эффекты попаданий','Частицы от попаданий и устранения заражённых.'],['contrast','Повышенный контраст','Более чёткие границы панелей и яркие подписи.']].map(([k,title,desc])=>'<label class="setting-row"><span><b>'+title+'</b><small>'+desc+'</small></span><input type="checkbox" data-setting="'+k+'" '+(prefs[k]?'checked':'')+'><i></i></label>').join('')+'</div><div class="settings-card controls-guide"><span class="eyebrow">ПОЛЕВАЯ ПАМЯТКА</span><h3>Держи дистанцию.</h3><p><kbd>W A S D</kbd> или стрелки — движение</p><p><kbd>SHIFT</kbd> / <kbd>ПРОБЕЛ</kbd> — бег</p><p><kbd>ESC</kbd> — пауза</p><p>На телефоне: джойстик слева, бег справа. Стрельба автоматическая.</p><span class="settings-version">ОБИТЕЛЬ · ВЕРСИЯ 0.6</span></div></div>';profileEditor(el,playerProfile,api,toast,showProfile);el.querySelectorAll('[data-setting]').forEach(input=>input.onchange=()=>{prefs[input.dataset.setting]=input.checked;localStorage.setItem(prefsKey,JSON.stringify(prefs));document.body.classList.toggle('high-contrast',prefs.contrast);setSprint(false)})}

async function initializeGame(){
 $('#retry-connection').onclick=connect;refresh();loadArt().then(refresh).catch(()=>toast('Часть графики не загрузилась. Можно продолжить игру.'));requestAnimationFrame(frame);await connect();setInterval(()=>{if(networkReady)energyHud();if(page==='raids'&&raid&&!busy)pollRaid()},4000);const invited=launchValue('raid');if(invited&&/^[a-f0-9]{12}$/.test(invited)){try{raid=(await api('raids/'+invited)).raid;navigate('raids')}catch(e){toast(e.message)}}
 if(launchValue('friend'))navigate('friends');
}
initializeGame().catch(()=>window.obitelStartupFailure?.('GAME_START'));
