import {medalMarkup} from './player-profile-ui.js';
export function profileEditor(root,profile,api,toast,onSave){
 const panel=document.createElement('section');panel.className='settings-card profile-editor';
 const earned=(profile.medals||[]).filter(m=>m.earned),selected=new Set(profile.displayMedals??profile.dossier?.display?.map(m=>m.id)??earned.slice(0,3).map(m=>m.id));
 panel.innerHTML='<span class="eyebrow">ЛИЧНОЕ ДЕЛО</span><h2>Твой позывной.</h2><form><label for="player-name">Ник игрока</label><input id="player-name" name="name" minlength="2" maxlength="32" required autocomplete="nickname"><button class="primary" type="submit">Сохранить позывной</button><p role="status" class="profile-status"></p></form><div class="section-title"><h3>Доска трофеев</h3><small>До 3 медалей в профиле</small></div><div class="medal-picker">'+(earned.map(m=>'<button type="button" class="medal-choice" data-medal="'+m.id+'" aria-pressed="'+selected.has(m.id)+'">'+medalMarkup(m)+'</button>').join('')||'<p>Заверши вылазки и побеждай боссов, чтобы получить первые медали.</p>')+'</div>'+(earned.length?'<button type="button" class="secondary" id="save-medals">Сохранить доску</button>':'')+'<details class="medal-journal"><summary>Все достижения</summary><div class="medal-picker">'+(profile.medals||[]).map(m=>'<div class="medal-progress '+(m.earned?'earned':'')+'"><b>'+m.title+'</b><span>'+m.progress+' / '+m.goal+'</span><small>'+m.description+'</small></div>').join('')+'</div></details>';
 panel.querySelector('input').value=profile.name||'';
 panel.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=panel.querySelector('[type=submit]');button.disabled=true;try{const data=await api('profile',{name:panel.querySelector('input').value});onSave(data);panel.querySelector('.profile-status').textContent='Позывной сохранён';toast('Позывной обновлён')}catch(error){panel.querySelector('.profile-status').textContent=error.message}finally{button.disabled=false}};
 panel.querySelectorAll('[data-medal]').forEach(b=>b.onclick=()=>{const id=b.dataset.medal;if(selected.has(id))selected.delete(id);else if(selected.size<3)selected.add(id);else{toast('На доске помещаются три медали');return;}b.setAttribute('aria-pressed',selected.has(id));});
 panel.querySelector('#save-medals')?.addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{onSave(await api('profile/medals',{medals:[...selected]}));toast('Доска трофеев сохранена')}catch(error){toast(error.message)}finally{b.disabled=false}});
 root.prepend(panel);
}
