import {drawWeapon,drawItem,drawRaidItem,loadRaidKit} from './art.js';
import {RAID_ATTACKS,raidAttackPlan} from './raid-attacks.js';
import {observeRaid,raidRanking} from './raid-observation.js';
import {MAPS,BOSS_COST,raidProfile,playerLevel,unlocked,WEAPONS} from './balance.js';
import {RARE_RAIDS,RAID_CAPACITY,raidAllowed} from './rare-raids.js';
export const BOSS_ART=['watcher','arsonist','crane','doctor','root','driver','smelter','admiral'];
const roles=['Хранитель пустых домов','Огонь последней заправки','Хозяин грузового двора','Карантин не окончен','Сердце заражённого леса','Последний рейс','Жар мёртвых печей','Командир затонувшего флота'];
const observations=new WeakMap();
const fmt=n=>Math.floor(n||0).toLocaleString('ru-RU');
const share=(damage,max)=>{const percent=damage/max*100;return percent>0&&percent<.01?'меньше 0,01%':percent.toLocaleString('ru-RU',{maximumFractionDigits:2})+'%'};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rewards=r=>Object.entries({scrap:'Детали',xp:'Опыт',cores:'Ядра',cloth:'Ткань'}).map(([k,name])=>'<div>'+(k==='xp'?'<i class="raid-xp-seal" aria-hidden="true">XP</i>':'<canvas data-raid-resource="'+({scrap:0,cores:1,cloth:2}[k])+'" width="42" height="42" aria-hidden="true"></canvas>')+'<span><strong>'+fmt(r[k])+'</strong><small>'+name+'</small></span></div>').join('');
const options=(raid,save,map,rare)=>RAID_ATTACKS.map(a=>raid?.attackOptions?.find(o=>o.id===a.id)||raidAttackPlan(save,map,rare,a.id,raid?.hp??Infinity,raid?.paymentMode==='test'));

export function tickRaid(root,raid,save,offset){
 if(!raid)return;
 const seconds=Math.max(0,Math.ceil((raid.nextAttack-Date.now()-offset)/1000));
 const blocked=!!raid.blockedBy||!raid.joined||!(raid.allowed??raidAllowed(save,raid.map,raid.rare))||raid.hp<=0;
 for(const attack of options(raid,save,raid.map,raid.rare)){
  const button=root.querySelector('[data-raid-attack="'+attack.id+'"]');if(!button)continue;
  const missing=!!attack.sku&&!attack.charges;
  button.disabled=blocked||attack.locked||!!raid.arenaPending||seconds>0||save.energy<attack.cost||missing||(attack.id!=='gun'&&raid.attackVersion!==2);
  button.textContent=raid.hp<=0?'Босс повержен':raid.blockedBy?'Другой босс активен':!raid.joined?'Нужен отряд':attack.locked?'Ур. '+attack.level:raid.arenaPending?'Заверши арену':missing?'Нет зарядов':seconds?'Через '+seconds+' с':save.energy<attack.cost?'Нужно '+attack.cost+' энергии':attack.id==='gun'?'Выстрелить':'Нанести удар';
 }
 const status=raid.blockedBy?'Сначала победи своего босса':!raid.joined?'Присоединись к отряду':raid.hp<=0?'Босс повержен':raid.arenaPending?'Бой на арене начат':seconds?'Подготовка · '+seconds+' с':save.energy<BOSS_COST?'Нужно 12 энергии':'Выбери удар';
 const clock=root.querySelector('#raid-ready-clock');if(clock)clock.textContent=status;
 const progress=root.querySelector('.raid-recovery>i');if(progress)progress.style.width=(seconds?Math.max(0,Math.min(100,(1-seconds/((raid.attackCooldown||raidProfile(raid.map).cooldown)/1000))*100)):100)+'%';
 const arena=root.querySelector('#raid-arena');if(arena){arena.disabled=raid.arenaVersion!==1||blocked||(!raid.arenaPending&&(seconds>0||save.energy<BOSS_COST));arena.textContent=raid.arenaPending?'Продолжить бой':seconds?'Арена · '+seconds+' с':'На арену · 12 ϟ';}
}

export function renderRaidView(root,{raid,save,selected,rareMode,offset,onMode,onMap,onCreate,onAttack,onBuy,onArena,onJoin,onClaim,onClose,onPrepare,onProfile,payments={mode:'off',account:'guest'}}){
 const map=raid?raid.map:selected,rare=raid?!!raid.rare:rareMode,m=raid?.clanBoss?{...MAPS[map],boss:raid.clanBoss.name}:MAPS[map],role=raid?.clanBoss?.role||roles[map],profile=RARE_RAIDS[map],allowed=raid?.allowed??raidAllowed(save,map,rare),mine=raid?.members.find(p=>p.me);
 const hp=raid?.hp??(rare?profile.hp:raidProfile(map).hp),maxHp=raid?.maxHp??hp,party=raid?.members||[],capacity=raid?.capacity||RAID_CAPACITY;
 const requiredLevel=raid?.clanBoss?.level||(rare?profile.level:m.level),remaining=Math.max(0,3-(save.districtRuns[map]||0));
 const accessReason=allowed?'Босс доступен':!unlocked(save,map)?'Победи босса предыдущего района':playerLevel(save)<requiredLevel?'Нужен уровень '+requiredLevel:remaining?'Ещё '+remaining+' зачистки района':rare&&!save.cleared.includes(map)?'Сначала обычная версия':'Нужен прогресс района';
 const encounter=raid?.id||'catalog-'+map+'-'+rare,same=root.dataset.encounter===encounter;
 const oldParty=root.querySelector('.raid-party')?.open,oldLoot=root.querySelector('.raid-loot')?.open,oldPage=Number(root.dataset.partyPage||0);
 const main=root.closest('main'),scroll=main?.scrollTop||0,focused=root.contains(document.activeElement)?document.activeElement.id:null;
 const previous=observations.get(root),seen=raid?observeRaid(previous,raid,Date.now()+offset):null;
 observations.set(root,seen);root.dataset.encounter=encounter;root.dataset.partyPage=String(same?oldPage:0);
 const leaders=raidRanking(party).slice(0,5),contribution=mine?.damage||0;
 const attacks=options(raid,save,map,rare),buyReady=payments.mode!=='off'&&payments.account==='vk';
 const feedback=same&&Number(root.dataset.hitAt)>Date.now()-2200?'<span class="raid-impact">−'+fmt(Number(root.dataset.hitDamage))+'</span>':'';
 const card=a=>`<section class="raid-command ${a.sku?'raid-command-extra':'raid-command-fire'}"><div class="raid-command-art"><canvas ${a.sku?'data-raid-item="'+a.art+'"':'data-raid-weapon="'+save.weapon+'"'} width="256" height="180" aria-hidden="true"></canvas>${a.sku?'<span class="raid-bonus">+'+a.bonus*100+'%</span>':'<span class="raid-standard">СНАРЯЖЕНО</span>'}</div><div class="raid-command-copy"><h3>${escape(a.name)}</h3><p>${a.sku?'Выстрел + '+fmt(a.extra)+' доп. урона':escape(WEAPONS[save.weapon].name)}</p><div class="raid-command-values"><span><b>${fmt(a.expected)}</b> урона</span><span>${a.cost} ϟ</span></div></div>${a.sku?'<small class="raid-ammo">'+(a.charges?'Зарядов: '+fmt(a.charges):a.pack+' ударов · '+a.votes+' '+(a.votes<5?'голоса':'голосов'))+'</small>':'<small class="raid-ammo">Без расходников</small>'}${raid?'<button class="'+(a.id==='gun'?'primary':'secondary')+'" id="strike-'+a.id+'" data-raid-attack="'+a.id+'" aria-describedby="raid-ready-clock">'+(a.id==='gun'?'Выстрелить':'Нанести удар')+'</button>':'<button class="secondary" disabled>'+(allowed?'Активируй босса':'Босс закрыт')+'</button>'}${a.sku&&raid&&!a.locked&&!a.charges&&hp>0?'<button class="raid-buy" id="buy-'+a.id+'" data-raid-buy="'+a.id+'" '+(!buyReady?'disabled':'')+'>'+(!buyReady?(payments.account!=='vk'?'Покупки внутри VK':'Покупки недоступны'):'Купить · '+a.votes+' '+(a.votes<5?'голоса':'голосов'))+'</button>':''}</section>`;
 root.innerHTML=`<div class="raid-toolbar"><div class="raid-tabs" role="group" aria-label="Тип босса">${raid&&hp>0?`<span class="raid-active-state">${raid.clanBoss?'Клановый':rare?'Редкий':'Обычный'} рейд · ${raid.blockedBy?'просмотр':'активен'}</span>`:`<button class="secondary" data-mode="normal" aria-pressed="${!rare}">Обычные</button><button class="secondary" data-mode="rare" aria-pressed="${rare}">Редкие</button>`}</div>${!raid?`<select id="raid-map" class="boss-select" aria-label="Выбрать босса">${MAPS.map((v,i)=>`<option value="${i}" ${map===i?'selected':''}>${v.boss}${rare?' · ур. '+RARE_RAIDS[i].level:''}</option>`).join('')}</select>`:`<small>${party.length} / ${capacity} бойцов</small>`}</div>
 <article class="raid-console ${rare?'is-rare':''}">
  <div class="raid-dossier"><div class="boss-stage" style="--boss-scene:url('assets/district-${map}.webp')"><span class="boss-rarity">${rare?'РЕДКАЯ ЦЕЛЬ':'ЦЕЛЬ '+String(map+1).padStart(2,'0')}</span><img class="boss-character" src="assets/boss-${BOSS_ART[map]}.png" alt="${escape(m.boss)} — ${role}" width="512" height="512" decoding="async">${feedback}<span class="boss-stage-caption">${escape(m.name)}</span></div>
  <div class="raid-vitals"><span>${role}</span><h2>${m.boss}</h2><div class="boss-hp-label"><b>${fmt(hp)}</b><span>/ ${fmt(maxHp)} HP</span></div><div class="raid-health" role="progressbar" aria-label="Здоровье босса" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(hp/maxHp*10000)/100}" aria-valuetext="${fmt(hp)} из ${fmt(maxHp)} HP"><i style="width:${hp/maxHp*100}%"></i></div><small>${raid?'Твой вклад: '+fmt(contribution):'Уровень '+requiredLevel+' · 3 зачистки'}</small>${raid&&hp>0&&raid.arenaVersion===1?'<button class="secondary" id="raid-arena">На арену · 12 ϟ</button>':''}</div></div>
  <div class="raid-command-center"><div class="raid-command-header"><div><span class="eyebrow">${raid?'ОБЩИЙ БОЙ':'АРСЕНАЛ РЕЙДА'}</span><span id="raid-ready-clock" tabindex="-1">${raid?'Выбери удар':accessReason}</span></div>${!raid?(allowed?'<button class="primary" id="create-raid">Активировать босса</button>':'<button class="secondary" id="raid-prepare">К району</button>'):!raid.joined&&hp>0?'<button class="primary" id="join-raid" '+(raid.blockedBy||!allowed||party.length>=capacity?'disabled':'')+'>Присоединиться</button>':''}</div>
   ${raid&&hp>0?'<div class="raid-recovery" aria-hidden="true"><i></i></div>':''}
   <div class="raid-command-grid">${raid&&hp<=0?'<div class="raid-victory"><span>ЦЕЛЬ УСТРАНЕНА</span><h3>Общая победа</h3><p>Твой вклад: '+fmt(contribution)+' урона.</p></div>':attacks.map(card).join('')}</div>
   ${raid?`<details class="raid-loot" ${hp<=0||oldLoot&&same?'open':''}><summary>${hp>0?'Награда после победы':'Твоя награда'}<span>${fmt(contribution)} урона · ${share(contribution,maxHp)}</span></summary><div class="raid-loot-title"><small>${rare||raid.clanBoss?'Фонд делится по фактическому урону.':hp>0?'До полной награды: '+fmt(Math.max(0,Math.ceil(maxHp*.25-contribution)))+' урона.':'Итог по твоему вкладу.'}</small></div><div class="raid-rewards">${rewards(raid.reward)}</div>${hp===0&&mine?.damage&&!mine.claimed?'<button class="primary" id="raid-claim">Забрать награду</button>':mine?.claimed?'<p class="raid-loot-claimed">Награда получена</p>':''}</details>`:''}
  </div>
 </article>
 ${raid?`<div class="raid-after-action"><section class="raid-activity"><div class="raid-block-title"><h3>Ход боя</h3><small>С начала просмотра</small></div>${seen.entries.length?'<ol>'+seen.entries.map(e=>`<li><time>${new Date(e.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</time><span>Общий урон <b>+${fmt(e.damage)}</b><small>${e.mine?'Твой вклад +'+fmt(e.mine):'Вклад других участников'} · осталось ${fmt(e.hp)} HP</small></span></li>`).join('')+'</ol>':'<p>Атаки отряда появятся здесь.</p>'}</section><section class="raid-damage-ranking"><div class="raid-block-title"><h3>Лидеры по урону</h3><small>В этом рейде</small></div>${leaders.length?'<ol>'+leaders.map((p,i)=>`<li ${p.me?'class="is-me"':''}><span class="damage-rank">${i+1}</span><span class="damage-player"><button class="player-name-link" data-player="${escape(p.code||'')}">${escape(p.name)}${p.me?' · ты':''}</button><small>${share(p.damage,maxHp)} здоровья босса</small></span><b>${fmt(p.damage)}</b></li>`).join('')+'</ol>':'<p>Первый удар откроет рейтинг.</p>'}</section></div>`:''}
 ${raid?((raid.blockedBy||hp<=0)?'<div class="raid-controls"><button class="secondary" id="close-raid">'+(raid.blockedBy?'К моему боссу':'К списку боссов')+'</button></div>':'')+`<details class="raid-party" ${oldParty&&same?'open':''}><summary>Весь отряд · ${party.length} / ${capacity}</summary><div class="party-list"></div><div class="party-pagination"></div></details>`:''}`;
 root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>onMode(b.dataset.mode==='rare'));
 const bind=(id,fn)=>{const el=root.querySelector('#'+id);if(el)el.onclick=fn};
 const select=root.querySelector('#raid-map');if(select)select.onchange=e=>onMap(Number(e.target.value));
 bind('raid-prepare',onPrepare);bind('raid-arena',onArena);bind('create-raid',onCreate);bind('join-raid',onJoin);bind('raid-claim',onClaim);bind('close-raid',onClose);
 root.querySelectorAll('[data-raid-attack]').forEach(b=>b.onclick=()=>onAttack(b.dataset.raidAttack));
 root.querySelectorAll('[data-raid-buy]').forEach(b=>b.onclick=()=>onBuy(b.dataset.raidBuy));
 root.querySelectorAll('[data-raid-weapon]').forEach(c=>drawWeapon(c,Number(c.dataset.raidWeapon)));
 const drawKit=()=>root.querySelectorAll('[data-raid-item]').forEach(c=>drawRaidItem(c,Number(c.dataset.raidItem)));
 drawKit();loadRaidKit().then(drawKit).catch(()=>{});
 root.querySelectorAll('[data-raid-resource]').forEach(c=>drawItem(c,Number(c.dataset.raidResource)));
 if(raid){const sorted=[...party].sort((a,b)=>b.damage-a.damage),pages=Math.ceil(sorted.length/20);
 const paint=()=>{const page=Math.min(Number(root.dataset.partyPage),Math.max(0,pages-1));root.dataset.partyPage=page;root.querySelector('.party-list').innerHTML=sorted.slice(page*20,page*20+20).map(p=>`<div><span><button class="player-name-link" data-player="${escape(p.code||'')}">${escape(p.name)}${p.me?' · ТЫ':''}</button><small>${p.online?'В сети':'Не в сети'}</small></span><div class="party-contribution"><b>${fmt(p.damage)} урона</b><div><i style="width:${Math.min(100,p.damage/maxHp*100)}%"></i></div></div>${p.claimed?'<small>Награда получена</small>':''}</div>`).join('');const nav=root.querySelector('.party-pagination');nav.innerHTML=pages>1?`<button class="secondary" ${page===0?'disabled':''} aria-label="Предыдущие участники">←</button><span>${page+1} / ${pages}</span><button class="secondary" ${page===pages-1?'disabled':''} aria-label="Следующие участники">→</button>`:'';root.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>onProfile?.(b.dataset.player));const buttons=nav.querySelectorAll('button');if(buttons.length){buttons[0].onclick=()=>{root.dataset.partyPage=page-1;paint()};buttons[1].onclick=()=>{root.dataset.partyPage=page+1;paint()};}};paint();tickRaid(root,raid,save,offset);}
 if(main)main.scrollTop=same?scroll:0;const focus=focused&&root.querySelector('#'+focused);if(focus&&!focus.disabled)focus.focus({preventScroll:true});else if(focus?.disabled)root.querySelector('#raid-ready-clock')?.focus({preventScroll:true});
}
