import {arenaContract} from './boss-arena.js';
import {portrait} from './friends-ui.js';
import {drawWeapon,drawItem} from './art.js';
import {observeRaid,raidRanking} from './raid-observation.js';
import {MAPS,BOSS_COST,raidProfile,playerLevel,unlocked,WEAPONS} from './balance.js';
import {RARE_RAIDS,RAID_CAPACITY,raidAllowed,raidHit} from './rare-raids.js';
export const BOSS_ART=['watcher','arsonist','crane','doctor','root','driver','smelter','admiral'];
const roles=['Хранитель пустых домов','Огонь последней заправки','Хозяин грузового двора','Карантин не окончен','Сердце заражённого леса','Последний рейс','Жар мёртвых печей','Командир затонувшего флота'];
const observations=new WeakMap();
const fmt=n=>Math.floor(n||0).toLocaleString('ru-RU');
const share=(damage,max)=>{const percent=damage/max*100;return percent>0&&percent<.01?'меньше 0,01%':percent.toLocaleString('ru-RU',{maximumFractionDigits:2})+'%'};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rewards=r=>Object.entries({scrap:'Детали',xp:'Опыт',cores:'Ядра',cloth:'Ткань'}).map(([k,name])=>'<div>'+(k==='xp'?'<i class="raid-xp-seal" aria-hidden="true">XP</i>':'<canvas data-raid-resource="'+({scrap:0,cores:1,cloth:2}[k])+'" width="42" height="42" aria-hidden="true"></canvas>')+'<span><strong>'+fmt(r[k])+'</strong><small>'+name+'</small></span></div>').join('');

export function tickRaid(root,raid,save,offset){
 const button=root.querySelector('#raid-attack');if(!button||!raid)return;
 const seconds=Math.max(0,Math.ceil((raid.nextAttack-Date.now()-offset)/1000));
 const blocked=!!raid.blockedBy||!raid.joined||!raidAllowed(save,raid.map,raid.rare)||raid.hp<=0;
 button.disabled=blocked||!!raid.arenaPending||seconds>0||save.energy<BOSS_COST;
 button.textContent=raid.hp<=0?'Босс повержен':raid.arenaPending?'Заверши арену':seconds?'Подготовка':'Атаковать';
 const status=raid.blockedBy?'Сначала победи активного босса':!raid.joined?'Присоединись к отряду':raid.hp<=0?'Общая победа':raid.arenaPending?'Начат бой на арене':seconds?'Отряд возвращается · '+seconds+' с':save.energy<BOSS_COST?'Нужно 12 энергии':'Отряд готов к атаке';
 const clock=root.querySelector('#raid-ready-clock');if(clock)clock.textContent=status;
 const arena=root.querySelector('#raid-arena');if(arena){arena.disabled=raid.arenaVersion!==1||blocked||(!raid.arenaPending&&(seconds>0||save.energy<BOSS_COST));arena.textContent=raid.arenaVersion!==1?'Сервер обновляется':raid.hp<=0?'Босс повержен':raid.arenaPending?'Продолжить бой':seconds?'Подготовка':'Вступить в бой';}
 const practice=root.querySelector('#arena-practice');if(practice)practice.disabled=!!raid.arenaPending;
 const cost=root.querySelector('.raid-arena-cost');if(cost)cost.textContent=raid.arenaPending?'Оплачено':'12 энергии';
}

export function renderRaidView(root,{raid,save,selected,rareMode,offset,onMode,onMap,onCreate,onAttack,onArena,onPractice,onJoin,onClaim,onClose,onPrepare}){
 const map=raid?raid.map:selected,rare=raid?!!raid.rare:rareMode,m=MAPS[map],profile=RARE_RAIDS[map],allowed=raidAllowed(save,map,rare),mine=raid?.members.find(p=>p.me);
 const reward=raid?.reward||{scrap:m.reward*2,xp:45,cores:3,cloth:6},capacity=raid?.capacity||RAID_CAPACITY,arena=arenaContract(save,map,rare);
 const hit=raid?.estimatedDamage??raidHit(save,map,rare),hp=raid?.hp??(rare?profile.hp:raidProfile(map).hp),maxHp=raid?.maxHp??hp,party=raid?.members||[];
 const requiredLevel=rare?profile.level:m.level,remaining=Math.max(0,3-(save.districtRuns[map]||0));
 const accessReason=allowed?'Доступ открыт':!unlocked(save,map)?'Победи босса предыдущего района':playerLevel(save)<requiredLevel?'Нужен уровень '+requiredLevel:remaining?'Осталось зачисток: '+remaining:rare&&!save.cleared.includes(map)?'Победи обычную версию':'Нужен прогресс района';
 const encounter=raid?.id||'catalog-'+map+'-'+rare,same=root.dataset.encounter===encounter;
 const oldArena=root.querySelector('.arena-guide')?.open,oldDetails=root.querySelector('.raid-rules')?.open,oldParty=root.querySelector('.raid-party')?.open,oldPage=Number(root.dataset.partyPage||0);
 const main=root.closest('main'),scroll=main?.scrollTop||0,focused=root.contains(document.activeElement)?document.activeElement.id:null;
 const previous=observations.get(root),seen=raid?observeRaid(previous,raid,Date.now()+offset):null;
 observations.set(root,seen);root.dataset.encounter=encounter;root.dataset.partyPage=String(same?oldPage:0);
 const leaders=raidRanking(party).slice(0,5),contribution=mine?.damage||0;
 const lootLabel=raid?(hp>0?'Твоя доля после победы':'Твоя награда'):rare?'Общий фонд отряда':'Максимальная награда';
 const lootHint=raid&&hp<=0?'Итог по твоему вкладу.':rare?'Фонд делится по фактическому урону.':raid?'До полной награды: '+fmt(Math.max(0,Math.ceil(maxHp*.25-contribution)))+' урона.':'Полная награда — за 25% здоровья босса.';
 const quickAction=!raid?allowed?'<button class="primary" id="create-raid">Начать рейд</button>':'<button class="primary" id="raid-prepare">К району</button>':'<button class="primary" id="raid-attack" aria-describedby="raid-ready-clock">Атаковать</button>';
 const arenaAction=!raid?'<button class="secondary" id="arena-practice">Тренировка</button>':'<button class="secondary" id="raid-arena" aria-describedby="raid-ready-clock">Вступить в бой</button>';
 root.innerHTML=`<div class="raid-toolbar"><div class="raid-tabs" role="group" aria-label="Тип босса">${raid&&hp>0?`<span class="raid-active-state">${rare?'Редкий':'Обычный'} рейд · ${raid.blockedBy?'просмотр':'активен'}</span>`:`<button class="secondary" data-mode="normal" aria-pressed="${!rare}">Обычные</button><button class="secondary" data-mode="rare" aria-pressed="${rare}">Редкие</button>`}</div>${!raid?`<select id="raid-map" class="boss-select" aria-label="Выбрать босса">${MAPS.map((v,i)=>`<option value="${i}" ${map===i?'selected':''}>${v.boss}${rare?' · ур. '+RARE_RAIDS[i].level:''}</option>`).join('')}</select>`:''}</div>
 <article class="raid-console ${rare?'is-rare':''}">
  <div class="raid-dossier"><div class="boss-stage" style="--boss-scene:url('assets/district-${map}.webp')"><span class="boss-rarity">${rare?'РЕДКАЯ ЦЕЛЬ':'ЦЕЛЬ '+String(map+1).padStart(2,'0')}</span><img class="boss-character" src="assets/boss-${BOSS_ART[map]}.png" alt="${escape(m.boss)} — ${roles[map]}" width="512" height="512" decoding="async"><span class="boss-stage-caption">${escape(m.name)}</span></div>
  <div class="raid-vitals"><span>${roles[map]}</span><h2>${m.boss}</h2><div class="boss-hp-label"><b>${fmt(hp)}</b><span>/ ${fmt(maxHp)} HP</span></div><div class="raid-health" role="progressbar" aria-label="Здоровье босса" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(hp/maxHp*10000)/100}" aria-valuetext="${fmt(hp)} из ${fmt(maxHp)} HP"><i style="width:${hp/maxHp*100}%"></i></div><small>${raid?'Общий урон: '+fmt(maxHp-hp):'Уровень '+requiredLevel+' · 3 зачистки'}</small></div></div>
  <div class="raid-command-center"><div class="raid-command-header"><span class="eyebrow">${raid?'БОЙ С ОТРЯДОМ':'ПОДГОТОВКА К БОЮ'}</span><span>${party.length} / ${capacity} бойцов</span></div>
   <div class="raid-command-grid"><section class="raid-command raid-command-fire"><div class="raid-command-art"><canvas data-raid-weapon="${save.weapon}" width="190" height="72" aria-hidden="true"></canvas><span>01 / ОРУЖИЕ</span></div><div class="raid-command-copy"><h3>Быстрый налёт</h3><p>${escape(WEAPONS[save.weapon].name)} · без управления</p><div class="raid-command-values"><span><b>${fmt(hit)}</b> урона</span><span><b>12</b> энергии</span></div></div>${quickAction}<small>Перерыв: ${raidProfile(map).cooldown/1000} сек</small></section>
   <section class="raid-command raid-command-arena"><div class="raid-command-art arena-command-art"><span>02 / ТАКТИКА</span></div><div class="raid-command-copy"><h3>Бой на платформе</h3><p>Уклоняйся и находи окно для стрельбы</p><div class="raid-command-values"><span>${raid?'до':'В рейде до'} <b>${fmt(arena.cap)}</b> урона</span><span class="raid-arena-cost">${raid?'12 энергии':'Бесплатная проба'}</span></div></div>${arenaAction}<small>${raid?'30 сек боя · общий перерыв':'Тренировка не наносит урон рейду'}</small></section></div>
   <div class="raid-readiness"><span id="raid-ready-clock" tabindex="-1">${raid?'Отряд готов к атаке':accessReason}</span>${!raid?`<small>Условия: уровень ${requiredLevel}${rare?' и победа над обычной версией':''}</small>`:!raid.joined&&hp>0?`<button class="secondary" id="join-raid" ${raid.blockedBy||!allowed||party.length>=capacity?'disabled':''}>${!allowed?'Нужен прогресс':party.length>=capacity?'Отряд заполнен':'Присоединиться'}</button>`:`<small>Твой вклад: ${fmt(contribution)} урона</small>`}</div>
   <section class="raid-loot"><div class="raid-loot-title"><b>${lootLabel}</b><small>${lootHint}</small></div><div class="raid-rewards">${rewards(raid?reward:rare?profile.pool:reward)}</div>${raid&&hp===0&&mine?.damage&&!mine.claimed?'<button class="primary" id="raid-claim">Забрать награду</button>':mine?.claimed?'<p class="raid-loot-claimed">Награда получена</p>':''}</section>
  </div>
 </article>
 ${raid?`<div class="raid-after-action"><section class="raid-activity"><div class="raid-block-title"><h3>Обновления боя</h3><small>С начала просмотра</small></div>${seen.entries.length?'<ol>'+seen.entries.map(e=>`<li><time>${new Date(e.at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</time><span>Общий урон <b>+${fmt(e.damage)}</b><small>${e.mine?'Твой вклад +'+fmt(e.mine):'Вклад других участников'} · осталось ${fmt(e.hp)} HP</small></span></li>`).join('')+'</ol>':'<p>Изменения появятся после следующей атаки. Старые события не восстанавливаются.</p>'}</section><section class="raid-damage-ranking"><div class="raid-block-title"><h3>Лидеры по урону</h3><small>В этом рейде</small></div>${leaders.length?'<ol>'+leaders.map((p,i)=>`<li ${p.me?'class="is-me"':''}><span class="damage-rank">${i+1}</span>${portrait(p)}<span class="damage-player">${escape(p.name)}${p.me?' · ты':''}<small>${share(p.damage,maxHp)} здоровья босса</small></span><b>${fmt(p.damage)}</b></li>`).join('')+'</ol>':'<p>Здесь появятся участники, которые уже нанесли урон.</p>'}</section></div>`:''}
 <div class="arena-tools">${raid?'<button class="secondary" id="arena-practice">Тренировка</button><p>Бесплатно · без опыта и наград</p>':''}<details class="arena-guide" ${oldArena&&same?'open':''}><summary>Тактика арены · 30 сек</summary><p>Наблюдение → подкрепление → ярость. Уходи из отмеченных зон, используй отпор и стреляй в окно уязвимости. Вклад отправляется после завершения боя. Максимум — до +20% к быстрому налёту.</p></details></div>
 <details class="raid-rules" ${oldDetails&&same?'open':''}><summary>Условия общего рейда</summary><p>У всех участников одно здоровье босса. Атакуй в удобное время; обновление вклада — каждые 4 секунды при открытом экране. Оба способа атаки стоят 12 энергии и используют общий перерыв. ${rare?'Осадное усиление ×'+profile.multiplier.toLocaleString('ru-RU',{maximumFractionDigits:2})+'. Общий фонд наград делится по урону; срока истечения рейда нет.':raidProfile(map).trait}</p><p>Один активный босс до победы. При выборе того же босса игра присоединяет к общему рейду, в первую очередь с друзьями. В отряде до 300 участников; при заполнении открывается следующий рейд.</p></details>
 ${raid?((raid.blockedBy||hp<=0)?'<div class="raid-controls"><button class="secondary" id="close-raid">'+(raid.blockedBy?'К моему боссу':'К списку боссов')+'</button></div>':'')+`<details class="raid-party" ${oldParty&&same?'open':''}><summary>Весь отряд · ${party.length} / ${capacity}</summary><div class="party-list"></div><div class="party-pagination"></div></details>`:''}`;
 root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>onMode(b.dataset.mode==='rare'));
 const bind=(id,fn)=>{const el=root.querySelector('#'+id);if(el)el.onclick=fn};
 const select=root.querySelector('#raid-map');if(select)select.onchange=e=>onMap(Number(e.target.value));
 bind('raid-prepare',onPrepare);bind('arena-practice',onPractice);bind('raid-arena',onArena);bind('create-raid',onCreate);bind('raid-attack',onAttack);bind('join-raid',onJoin);bind('raid-claim',onClaim);bind('close-raid',onClose);
 root.querySelectorAll('[data-raid-weapon]').forEach(c=>drawWeapon(c,Number(c.dataset.raidWeapon)));root.querySelectorAll('[data-raid-resource]').forEach(c=>drawItem(c,Number(c.dataset.raidResource)));
 if(raid){const sorted=[...party].sort((a,b)=>b.damage-a.damage),pages=Math.ceil(sorted.length/20);
 const paint=()=>{const page=Math.min(Number(root.dataset.partyPage),Math.max(0,pages-1));root.dataset.partyPage=page;root.querySelector('.party-list').innerHTML=sorted.slice(page*20,page*20+20).map(p=>`<div>${portrait(p)}<span><b>${escape(p.name)}${p.me?' · ТЫ':''}</b><small>${p.online?'В сети':'Не в сети'}</small></span><div class="party-contribution"><b>${fmt(p.damage)} урона</b><div><i style="width:${Math.min(100,p.damage/maxHp*100)}%"></i></div></div>${p.claimed?'<small>Награда получена</small>':''}</div>`).join('');const nav=root.querySelector('.party-pagination');nav.innerHTML=pages>1?`<button class="secondary" ${page===0?'disabled':''} aria-label="Предыдущие участники">←</button><span>${page+1} / ${pages}</span><button class="secondary" ${page===pages-1?'disabled':''} aria-label="Следующие участники">→</button>`:'';const buttons=nav.querySelectorAll('button');if(buttons.length){buttons[0].onclick=()=>{root.dataset.partyPage=page-1;paint()};buttons[1].onclick=()=>{root.dataset.partyPage=page+1;paint()};}};paint();tickRaid(root,raid,save,offset);}
 if(main)main.scrollTop=same?scroll:0;const focus=focused&&root.querySelector('#'+focused);if(focus&&!focus.disabled)focus.focus({preventScroll:true});else if(focus?.disabled)root.querySelector('#raid-ready-clock')?.focus({preventScroll:true});
}
