import {readFileSync,writeFileSync} from 'node:fs';
let b=readFileSync('balance.js','utf8');b=b.replace("damage:18,rate:.21,range:460,cost:180","damage:15,rate:.28,range:430,cost:360").replace("damage:17,rate:.72,range:230,pellets:5,cost:260","damage:13,rate:.82,range:240,pellets:5,cost:440").replace('Подпускай ближе — и уходи рывком.','Подпускай ближе и отходи бегом.').replace('s.armor*18','s.armor*12').replace('s.body*.06','s.body*.04').replace('s.weaponLevel*.12','s.weaponLevel*.08').replace('s.engine*.05','s.engine*.04').replace('s.trunk*.08','s.trunk*.05').replace('60*Math.pow(1.5,level)','80*Math.pow(1.42,level)');writeFileSync('balance.js',b);
let service=readFileSync('raid-service.js','utf8').replace('bossUnlocked,upgradeCost}','bossUnlocked,upgradeCost,runXP,raidDamage}');service=service.replace('xp=kills*4+(win?80:0)','xp=runXP(kills,win,t.map)').replace('s.xp+=100','s.xp+=45').replace('Math.round(st.damage*(weapon.pellets||1)/weapon.rate*6)','raidDamage(s)').replace('Date.now()-t.started>12000','Date.now()-t.started>18000');writeFileSync('raid-service.js',service);
let s=readFileSync('game.js','utf8');function change(a,b){if(!s.includes(a))throw Error(a.slice(0,80));s=s.replace(a,b)}
change('bossUnlocked}', 'bossUnlocked,levelProgress,sprintStep}');change('car,loadArt}', 'car,loadArt,setAppearance}');
change("let raid=null,serverOffset=0,networkReady=false,busy=false;",`let raid=null,serverOffset=0,networkReady=false,busy=false,sprintHeld=false;
const prefsKey='obitel-settings-v1';let prefs={particles:true,contrast:false,runToggle:false};try{prefs={...prefs,...JSON.parse(localStorage.getItem(prefsKey)||'{}')}}catch{}document.body.classList.toggle('high-contrast',prefs.contrast);
`);
change('function refresh(){rollDay();','function refresh(){setAppearance(save);rollDay();');change("$('#level').textContent=`Уровень ${playerLevel(save)}`;", "$('#level').textContent=`Уровень ${playerLevel(save)}`;let progress=levelProgress(save);$('#xp-fill').style.width=progress.percent+'%';$('#xp-caption').textContent=Math.floor(progress.current)+' / '+progress.required+' XP';");
change("if(page==='raids')renderRaids();", "if(page==='raids')renderRaids();if(page==='settings')renderSettings();");change("raids:'Один босс. Общая цель.'", "raids:'Один босс. Общая цель.',settings:'Настрой свой ритм.'");
change('shotCd:.2,dashCd:0,','shotCd:.2,stamina:100,exhausted:false,running:false,anim:0,moving:false,travel:0,transition:null,');
change("background(bg.getContext('2d'),selected);keys.clear();", "background(bg.getContext('2d'),selected);sprintHeld=false;keys.clear();");
const start=s.indexOf('function dash(){'),end=s.indexOf('function movement()',start);s=s.slice(0,start)+`function setSprint(value){sprintHeld=value;$('#dash').classList.toggle('running',value)}
function advanceSection(dt){let r=run,tr=r.transition;tr.elapsed+=dt;let f=Math.min(1,tr.elapsed/2.4),smooth=f*f*(3-2*f);r.travel=tr.start+960*smooth;r.x=tr.x+(190-tr.x)*smooth;r.anim+=dt*1.8;r.moving=true;r.running=true;if(f===1){r.transition=null;r.moving=false;r.running=false;spawnWave()}updateHud()}
function beginSection(){let r=run;for(let d of r.drops)if(d.kind==='scrap')r.loot+=d.amount;r.drops=[];r.shots=[];r.transition={elapsed:0,start:r.travel,x:r.x};$('#wave-label').textContent='ПУТЬ СВОБОДЕН · ДВИЖЕМСЯ ДАЛЬШЕ';}
`+s.slice(end);
change("if(e.code==='Space')dash();", "if(['ShiftLeft','ShiftRight','Space'].includes(e.code)&&!e.repeat){setSprint(prefs.runToggle?!sprintHeld:true)}");
change("addEventListener('keyup',e=>keys.delete(e.code));", "addEventListener('keyup',e=>{keys.delete(e.code);if(['ShiftLeft','ShiftRight','Space'].includes(e.code)&&!prefs.runToggle)setSprint(false)});");
change("$('#dash').onclick=dash;", "$('#dash').onpointerdown=e=>{e.preventDefault();$('#dash').setPointerCapture(e.pointerId);setSprint(prefs.runToggle?!sprintHeld:true)};$('#dash').onpointerup=$('#dash').onpointercancel=$('#dash').onlostpointercapture=()=>{if(!prefs.runToggle)setSprint(false)};");
s=s.replaceAll('keys.clear();stick={x:0,y:0};','keys.clear();setSprint(false);stick={x:0,y:0};');
change("function burst(x,y,color,n=5){for", "function burst(x,y,color,n=5){if(!prefs.particles)return;for");
change("r.time+=dt;r.dashCd=Math.max(0,r.dashCd-dt);r.invulnerable", "r.time+=dt;if(r.transition){advanceSection(dt);return}r.invulnerable");
change("r.x=Math.max(25,Math.min(935,r.x+dx/len*r.speed*dt));r.y=Math.max(275,Math.min(535,r.y+dy/len*r.speed*.8*dt));", "r.moving=Math.hypot(dx,dy)>.05;let sprint=sprintStep(r.stamina,r.exhausted,sprintHeld,r.moving,dt);Object.assign(r,sprint);r.anim+=r.moving?dt*(r.running?1.75:1):0;r.x=Math.max(25,Math.min(935,r.x+dx/len*r.speed*sprint.multiplier*dt));r.y=Math.max(275,Math.min(535,r.y+dy/len*r.speed*.8*sprint.multiplier*dt));");
change("spawnWave();r.next=1.8", "if(r.wave>0){beginSection();return}spawnWave();r.next=1.8");
change("$('#dash').innerHTML=r.dashCd>0?`${r.dashCd.toFixed(1)}<small>ПЕРЕЗАРЯДКА</small>`:'РЫВОК<small>ПРОБЕЛ</small>';$('#dash').disabled=r.dashCd>0;", "$('#dash').innerHTML=(r.exhausted?'ОТДЫХ':r.running?'БЕГ':'БЕЖАТЬ')+'<small>'+Math.ceil(r.stamina)+'%</small>';$('#dash').disabled=false;$('#stamina-fill').style.width=r.stamina+'%';$('#section-count').textContent='УЧАСТОК '+Math.max(1,r.wave)+' / 3';");
change("let r=run;g.drawImage(bg,0,0);", "let r=run;const offset=r.travel%960,section=Math.floor(r.travel/960);for(let tile=0;tile<2;tile++){let tx=tile*960-offset;g.save();g.translate(tx,0);if((section+tile)%2){g.translate(960,0);g.scale(-1,1)}g.drawImage(bg,0,0);g.restore();}if(r.transition){g.fillStyle='#14201490';g.fillRect(300,200,360,42);g.fillStyle='#edbd7c';g.font='17px monospace';g.textAlign='center';g.fillText('УЧАСТОК ЗАЧИЩЕН →',480,227);g.textAlign='left';}");
change("person(g,e.x,e.y,e.type,scale,r.time,hero?r.face:e.x>r.x?-1:1,e.flash)","person(g,e.x,e.y,e.type,scale,hero?r.anim:r.time,hero?r.face:e.x>r.x?-1:1,e.flash,hero?r.moving:true,hero?r.running:e.type==='runner')");
change("renderPage()}","renderPage()}");
change("<p class=\"page-intro\">Каждое оружие", "<div class=\"loadout-hero\"><canvas id=\"loadout-avatar\" width=\"400\" height=\"380\"></canvas><div><span class=\"eyebrow orange\">ТВОЙ ВЫЖИВШИЙ</span><h2>${save.armor?'Броня на месте.':'Начни с малого.'}</h2><p>${save.armor?'Бронежилет «Барьер», ур. '+save.armor:'Обычная футболка и походные брюки'}</p><strong>${WEAPONS[save.weapon].name}</strong><div class=\"stat-pills\"><span>${stats(save).hp} HP</span><span>${Math.round(stats(save).damage)} УРОН</span><span>${playerLevel(save)} УРОВЕНЬ</span></div></div></div><p class=\"page-intro\">Каждое оружие");
change("document.querySelectorAll('[data-upgrade]')", "if($('#loadout-avatar')){let c=$('#loadout-avatar');person(c.getContext('2d'),180,355,'hero',3,0,1,0,false)}document.querySelectorAll('[data-upgrade]')");
s=s.replaceAll('+12%','+8%').replaceAll('save.weaponLevel*12','save.weaponLevel*8').replaceAll('+18 здоровья','+12 здоровья').replaceAll('save.armor*18','save.armor*12').replaceAll('+5% урона','+4% урона').replaceAll('save.engine*5','save.engine*4').replaceAll('+6% здоровья','+4% здоровья').replaceAll('save.body*6','save.body*4').replaceAll('+8% деталей','+5% деталей').replaceAll('save.trunk*8','save.trunk*5');
s=s.replace('Пробел или правая кнопка — рывок с короткой неуязвимостью, перезарядка 4 секунды.','Удерживай Shift, пробел или кнопку «Бежать»: скорость выше на 65%, расходуется выносливость. Бег не даёт неуязвимость. После истощения восстанови 30%.').replace('Босс сам не появляется.','После волны отряд продвигается на следующий участок улицы. Босс сам не появляется.');
const settings=`
function renderSettings(){const el=$('#settings-page');el.innerHTML='<div class="settings-layout"><div class="settings-card"><span class="eyebrow orange">УПРАВЛЕНИЕ И ЭКРАН</span><h2>Под тебя.</h2><p>Настройки сохраняются на этом устройстве.</p>'+[['runToggle','Бег по нажатию','Включить бег одним нажатием вместо удержания.'],['particles','Эффекты попаданий','Частицы от попаданий и устранения заражённых.'],['contrast','Повышенный контраст','Более чёткие границы панелей и яркие подписи.']].map(([k,title,desc])=>'<label class="setting-row"><span><b>'+title+'</b><small>'+desc+'</small></span><input type="checkbox" data-setting="'+k+'" '+(prefs[k]?'checked':'')+'><i></i></label>').join('')+'</div><div class="settings-card controls-guide"><span class="eyebrow">ПОЛЕВАЯ ПАМЯТКА</span><h3>Держи дистанцию.</h3><p><kbd>W A S D</kbd> или стрелки — движение</p><p><kbd>SHIFT</kbd> / <kbd>ПРОБЕЛ</kbd> — бег</p><p><kbd>ESC</kbd> — пауза</p><p>На телефоне: джойстик слева, бег справа. Стрельба автоматическая.</p><span class="settings-version">ОБИТЕЛЬ · ВЕРСИЯ 0.3</span></div></div>';el.querySelectorAll('[data-setting]').forEach(input=>input.onchange=()=>{prefs[input.dataset.setting]=input.checked;localStorage.setItem(prefsKey,JSON.stringify(prefs));document.body.classList.toggle('high-contrast',prefs.contrast);setSprint(false)})}
`;
s=s.replace('await loadArt();',settings+'\nawait loadArt();');writeFileSync('game.js',s);
let html=readFileSync('index.html','utf8');html=html.replace('<span class="brand-mark">О<span>М</span></span>','<img class="brand-icon" src="assets/brand.png" alt="Эмблема Обители">').replace('<small>ВЫЖИТЬ. ВЕРНУТЬСЯ. ПОВТОРИТЬ.</small>','').replace('ПРОТОТИП / 0.2','АЛЬФА / 0.3').replace('<b id="level">Уровень 1</b>','<b id="level">Уровень 1</b><div class="xp-track"><i id="xp-fill"></i></div><small id="xp-caption"></small>').replace('</nav>','<button data-page="settings"><span>⚙</span> Настройки <small>07</small></button></nav>').replace('<section id="guide-page"','<section id="settings-page" class="page" hidden></section><section id="guide-page"').replace('пробел — рывок','Shift или пробел — бег').replace('ПРОБЕЛ — РЫВОК','SHIFT / ПРОБЕЛ — БЕГ').replace('<button id="dash">РЫВОК <small>ПРОБЕЛ</small></button>','<button id="dash">БЕЖАТЬ <small>УДЕРЖИВАЙ</small></button>').replace('<span id="kill-label">','<div class="stamina-track"><i id="stamina-fill"></i></div><span class="stamina-title">ВЫНОСЛИВОСТЬ</span><span id="section-count">УЧАСТОК 1 / 3</span><span id="kill-label">');writeFileSync('index.html',html);
