import {readFileSync as read,writeFileSync as write} from 'node:fs';
let d=read('domain.js','utf8');d="import {socialAction,ensureSocial} from './friends-domain.js';\n"+d;
d=d.replace("else if(req.method==='POST'&&path==='/api/upgrade')", "else if(path.startsWith('/api/friends'))result=socialAction(db,session,path,req.method,b,id);\n   else if(req.method==='POST'&&path==='/api/upgrade')");write('domain.js',d);
let g=read('game.js','utf8');g="import {friendsUI} from './friends-ui.js';\nimport {launchValue,inviteLink} from './platform.js';\n"+g;
g=g.replace("function renderPage(){", "function renderPage(){if(page==='friends')friendsUI($('#friends-page'),api,toast,async id=>{try{raid=(await api('raids/'+id)).raid;navigate('raids')}catch(e){toast(e.message)}});");
g=g.replace("settings:'Настрой свой ритм.'", "friends:'Свои не бросают.',settings:'Настрой свой ритм.'");
g=g.replace("await loadArt();await connect();", "refresh();loadArt().then(refresh).catch(()=>toast('Часть графики не загрузилась. Можно продолжить игру.'));await connect();");
g=g.replace("new URLSearchParams(location.search).get('raid')", "launchValue('raid')");
g=g.replace("location.origin+location.pathname+'?raid='+raid.id", "inviteLink('raid',raid.id)");
g+="\nif(launchValue('friend'))navigate('friends');\n";
write('game.js',g);
let client=read('client-api.js','utf8').replace("const crossOrigin=new URL(API_BASE).origin!==location.origin;", "const crossOrigin=new URL(API_BASE).origin!==location.origin;const tokenMode=crossOrigin||window.parent!==window;");
client=client.replace('if(crossOrigin&&token)','if(tokenMode&&token)').replace('if(crossOrigin&&issued','if(tokenMode&&issued');write('client-api.js',client);
let s=read('server.mjs','utf8').replace('client-api\\.js|','client-api\\.js|platform\\.js|friends-ui\\.js|');write('server.mjs',s);
let b=read('build.mjs','utf8').replace("'client-api.js',","'client-api.js','friends-ui.js',");write('build.mjs',b);
let html=read('index.html','utf8');
html=html.replace('</head>',`<meta name="description" content="Обитель Мёртвых — бесплатная онлайн-игра о выживании среди зомби. Зачищай районы, собирай ресурсы, улучшай оружие и броню, объединяйся с друзьями против боссов."><meta property="og:type" content="website"><meta property="og:title" content="Обитель Мёртвых — выживание среди зомби"><meta property="og:description" content="Исследуй заброшенный город, развивай выжившего и сражайся с боссами вместе с друзьями."><meta property="og:image" content="https://obitel-dead-beta.imdeantoo.chatgpt.site/assets/brand-beta.png"><meta property="og:url" content="https://obitel-dead-beta.imdeantoo.chatgpt.site/"><meta name="twitter:card" content="summary"><meta name="robots" content="index,follow"><link rel="canonical" href="https://obitel-dead-beta.imdeantoo.chatgpt.site/"><script type="module" src="platform.js"></script><script type="application/ld+json">{"@context":"https://schema.org","@type":"VideoGame","name":"Обитель Мёртвых","url":"https://obitel-dead-beta.imdeantoo.chatgpt.site/","description":"Онлайн-игра о выживании среди зомби: зачистка районов, развитие персонажа и совместные рейды на боссов.","genre":["Survival","Action","Role-playing"],"gamePlatform":"Web browser","inLanguage":"ru","isAccessibleForFree":true}</script></head>`);
html=html.replace('<button data-page="settings">','<button data-page="friends"><span>♧</span> Друзья <small>07</small></button><button data-page="settings">');
html=html.replace('<section id="settings-page"','<section id="friends-page" class="page" hidden></section><section id="settings-page"');
html=html.replace('<footer>',`<section class="about-game"><h2>Обитель Мёртвых</h2><p>Город опустел, но борьба за жизнь продолжается. Исследуй пять опасных районов, отбивай волны зомби и возвращайся в убежище с ресурсами. Создавай оружие, подбирай броню и улучшай свою мобильную базу.</p><p>Добавляй друзей, собирай отряд и атакуй сильных боссов. Каждый участник сражается в удобное время, приближая общую победу. Новые вылазки, ежедневные задания и развитие выжившего ждут тебя в Обители Мёртвых.</p></section><footer>`);
write('index.html',html);
