import test from 'node:test';
import assert from 'node:assert/strict';
import {MAPS,WEAPONS,freshSave,stats,upgradeCost,unlocked,enemyStats,restoreEnergy,spendEnergy,ENERGY_INTERVAL,bossUnlocked} from '../balance.js';
test('campaign gates maps in sequence and allows replay',()=>{let s=freshSave();assert.deepEqual(MAPS.map((_,i)=>unlocked(s,i)),[true,false,false,false,false]);s.cleared.push(0);assert.equal(unlocked(s,1),true);assert.equal(unlocked(s,2),false);assert.equal(unlocked(s,0),true)});
test('all three vehicle modules increase their respective actual stats',()=>{let s=freshSave(),base=stats(s);s.engine=1;assert.equal(stats(s).damage,base.damage*1.04);s.body=1;assert.ok(stats(s).hp>base.hp);s.trunk=1;assert.equal(stats(s).loot,1.05)});
test('upgrades stay finite across the full supported progression',()=>{for(let n=0;n<=10;n++){let s={...freshSave(),weaponLevel:n,armor:n,engine:n,body:n,trunk:n};for(let w=0;w<WEAPONS.length;w++){s.weapon=w;assert.ok(stats(s).damage>0);assert.ok(Number.isFinite(stats(s).hp))}assert.ok(upgradeCost(n)>0);if(n)assert.ok(upgradeCost(n)>upgradeCost(n-1))}});
test('five bosses scale and ordinary enemies retain distinct roles',()=>{assert.equal(MAPS.length,5);for(let m=0;m<5;m++){let boss=enemyStats(m,3,'boss'),walker=enemyStats(m,3,'walker'),runner=enemyStats(m,3,'runner'),tank=enemyStats(m,3,'tank');assert.ok(boss.hp>tank.hp);assert.ok(tank.hp>walker.hp);assert.ok(runner.speed>walker.speed);if(m)assert.ok(boss.hp>enemyStats(m-1,3,'boss').hp)}});
test('energy recovers exact intervals, preserves partial time and caps at maximum',()=>{let s=freshSave();assert.ok(spendEnergy(s,8,1000000));assert.equal(s.energy,52);restoreEnergy(s,1000000+ENERGY_INTERVAL*2+1000);assert.equal(s.energy,54);assert.equal(s.energyAt,1000000+ENERGY_INTERVAL*2);assert.equal(spendEnergy(s,55,1000000+ENERGY_INTERVAL*2+1000),false);restoreEnergy(s,1000000+ENERGY_INTERVAL*200);assert.equal(s.energy,60)});
test('clearing a district does not auto-unlock the next district or spawn a boss',()=>{let s=freshSave();s.districtRuns[0]=3;assert.equal(bossUnlocked(s,0),true);assert.equal(unlocked(s,1),false);s.cleared.push(0);assert.equal(unlocked(s,1),true);assert.equal(bossUnlocked(s,1),false)});
