import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {api} from '../worker.js';
import {freshSave,stats,migrateSave} from '../balance.js';

function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0000_noisy_old_lace.sql',import.meta.url),'utf8'));return {sqlite,prepare(sql){return {bind(...params){return {async first(){return sqlite.prepare(sql).get(...params)||null},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...params).changes)}}}}}}}}}
const request=(cookie,path,data)=>new Request('https://beta.example/api/'+path,{method:data===undefined?'GET':'POST',headers:{cookie:'obitel_session='+cookie,origin:'https://beta.example'},body:data===undefined?undefined:JSON.stringify(data)});
test('hosted guest cookie persists; origin protection rejects foreign sites',async()=>{const DB=database();const r=await api(request('','profile'),{DB});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);const token=cookie.match(/session=([a-f0-9]+)/)[1];const next=await api(request(token,'profile'),{DB});assert.equal(next.headers.get('set-cookie'),null);const first=await r.json(),second=await next.json();assert.equal(first.name,second.name);assert.equal(first.save.scrap,second.save.scrap);const bad=await api(new Request('https://beta.example/api/upgrade',{method:'POST',headers:{origin:'https://other.example'},body:'{}'}),{DB});assert.equal(bad.status,403);DB.sqlite.close()});
test('armor is gated, purchased once, equips and changes stats without changing ownership',async()=>{const DB=database(),id='a'.repeat(32),save={...freshSave(),scrap:3000,cloth:100,cores:15};const world={players:{[id]:{name:'Тестер',save}},raids:{}};DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify(world));let r=await api(request(id,'armor',{armor:1}),{DB});assert.equal(r.status,400);save.bossKills=1;DB.sqlite.prepare('UPDATE game_world SET data=?').run(JSON.stringify(world));r=await api(request(id,'armor',{armor:1}),{DB});const bought=(await r.json()).save;assert.equal(bought.armorTier,1);assert.equal(bought.scrap,2680);assert.equal(bought.cloth,92);assert.equal(stats(bought).hp,138);await api(request(id,'armor',{armor:0}),{DB});r=await api(request(id,'armor',{armor:1}),{DB});assert.equal((await r.json()).save.scrap,2680);DB.sqlite.close()});
test('simultaneous raid attacks retry stale snapshots and retain both contributions',async()=>{const DB=database(),a='a'.repeat(32),b='b'.repeat(32),rid='c'.repeat(12);const player=()=>({name:'Тестер',save:{...freshSave(),districtRuns:[3,0,0,0,0]}});DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify({players:{[a]:player(),[b]:player()},raids:{[rid]:{id:rid,map:0,owner:a,hp:750,maxHp:750,created:Date.now(),members:{[a]:{damage:0,nextAttack:0},[b]:{damage:0,nextAttack:0}}}}}));const responses=await Promise.all([a,b].map(id=>api(request(id,'raids/'+rid+'/attack',{}),{DB})));assert.ok(responses.every(r=>r.status===200));const world=JSON.parse(DB.sqlite.prepare('SELECT data FROM game_world').get().data);assert.equal(world.raids[rid].hp,292);assert.equal(world.raids[rid].members[a].damage,229);assert.equal(world.raids[rid].members[b].damage,229);assert.equal(world.players[a].save.energy,48);assert.equal(world.players[b].save.energy,48);DB.sqlite.close()});
test('migration preserves existing armor and unlocked sets',()=>{let s=freshSave();delete s.armorTier;delete s.ownedArmor;s.armor=3;migrateSave(s);assert.equal(s.armorTier,1);assert.deepEqual(s.ownedArmor,[0,1]);migrateSave(s);assert.equal(s.armor,3)});
