import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {api} from '../worker.js';
import {freshSave,stats,migrateSave} from '../balance.js';

function database(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0000_noisy_old_lace.sql',import.meta.url),'utf8'));return {sqlite,prepare(sql){return {bind(...params){return {async first(){return sqlite.prepare(sql).get(...params)||null},async run(){return {meta:{changes:Number(sqlite.prepare(sql).run(...params).changes)}}}}}}}}}
const request=(cookie,path,data)=>new Request('https://beta.example/api/'+path,{method:data===undefined?'GET':'POST',headers:{cookie:'obitel_session='+cookie,origin:'https://beta.example'},body:data===undefined?undefined:JSON.stringify(data)});
test('hosted guest cookie persists; origin protection rejects foreign sites',async()=>{const DB=database();const r=await api(request('','profile'),{DB});assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);const token=cookie.match(/session=([a-f0-9]+)/)[1];const next=await api(request(token,'profile'),{DB});assert.equal(next.headers.get('set-cookie'),null);const first=await r.json(),second=await next.json();assert.equal(first.name,second.name);assert.equal(first.save.scrap,second.save.scrap);const bad=await api(new Request('https://beta.example/api/upgrade',{method:'POST',headers:{origin:'https://other.example'},body:'{}'}),{DB});assert.equal(bad.status,403);DB.sqlite.close()});
test('armor is gated, purchased once, equips and changes stats without changing ownership',async()=>{const DB=database(),id='a'.repeat(32),save={...freshSave(),scrap:3000,cloth:100,cores:15};const world={players:{[id]:{name:'Тестер',save}},raids:{}};DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify(world));let r=await api(request(id,'armor',{armor:1}),{DB});assert.equal(r.status,400);save.bossKills=1;DB.sqlite.prepare('UPDATE game_world SET data=?').run(JSON.stringify(world));r=await api(request(id,'armor',{armor:1}),{DB});const bought=(await r.json()).save;assert.equal(bought.armorTier,1);assert.equal(bought.scrap,2680);assert.equal(bought.cloth,92);assert.equal(stats(bought).hp,138);await api(request(id,'armor',{armor:0}),{DB});r=await api(request(id,'armor',{armor:1}),{DB});assert.equal((await r.json()).save.scrap,2680);DB.sqlite.close()});
test('simultaneous raid attacks retry stale snapshots and retain both contributions',async()=>{const DB=database(),a='a'.repeat(32),b='b'.repeat(32),rid='c'.repeat(12);const player=()=>({name:'Тестер',save:{...freshSave(),districtRuns:[3,0,0,0,0]}});DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify({players:{[a]:player(),[b]:player()},raids:{[rid]:{id:rid,map:0,owner:a,hp:750,maxHp:750,created:Date.now(),members:{[a]:{damage:0,nextAttack:0},[b]:{damage:0,nextAttack:0}}}}}));const responses=await Promise.all([a,b].map(id=>api(request(id,'raids/'+rid+'/attack',{}),{DB})));assert.ok(responses.every(r=>r.status===200));const world=JSON.parse(DB.sqlite.prepare('SELECT data FROM game_world').get().data);assert.equal(world.raids[rid].hp,292);assert.equal(world.raids[rid].members[a].damage,229);assert.equal(world.raids[rid].members[b].damage,229);assert.equal(world.players[a].save.energy,48);assert.equal(world.players[b].save.energy,48);DB.sqlite.close()});
test('migration preserves existing armor and unlocked sets',()=>{let s=freshSave();delete s.armorTier;delete s.ownedArmor;s.armor=3;migrateSave(s);assert.equal(s.armorTier,1);assert.deepEqual(s.ownedArmor,[0,1]);migrateSave(s);assert.equal(s.armor,3)});

test('SourceCraft preflight and bearer sessions work without third-party cookies',async()=>{const DB=database(),origin='https://obitel.sourcecraft.site';const preflight=await api(new Request('https://beta.example/api/profile',{method:'OPTIONS',headers:{origin,'Access-Control-Request-Headers':'x-obitel-session'}}),{DB});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),origin);assert.equal(DB.sqlite.prepare('SELECT count(*) as n FROM game_world').get().n,0);const first=await api(new Request('https://beta.example/api/profile',{headers:{origin}}),{DB}),token=first.headers.get('x-obitel-session');assert.match(token,/^[a-f0-9]{32}$/);const r=await api(new Request('https://beta.example/api/upgrade',{method:'POST',headers:{origin,'x-obitel-session':token},body:JSON.stringify({field:'weaponLevel'})}),{DB});assert.equal(r.status,200);assert.equal((await r.json()).save.scrap,100);const next=await api(new Request('https://beta.example/api/profile',{headers:{origin,'x-obitel-session':token}}),{DB});assert.equal((await next.json()).save.weaponLevel,1);assert.equal(next.headers.get('x-obitel-session'),null);DB.sqlite.close()});

test('clan membership persists in D1 across independent sessions',async()=>{const DB=database(),a='a'.repeat(32),b='b'.repeat(32);const player=name=>({name,save:{...freshSave(),xp:240}});DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify({players:{[a]:player('Глава'),[b]:player('Участник')},raids:{}}));let r=await api(request(a,'clans/create',{name:'Север'}),{DB});assert.equal(r.status,200);const code=(await r.json()).clan.code;r=await api(request(b,'clans/request',{code}),{DB});assert.equal(r.status,200);r=await api(request(a,'clans'),{DB});const pending=(await r.json()).clan.requests;assert.equal(pending.length,1);r=await api(request(a,'clans/accept',{code:pending[0].code}),{DB});assert.equal(r.status,200);r=await api(request(b,'clans'),{DB});assert.equal((await r.json()).clan.members.length,2);DB.sqlite.close()});

test('nickname and avatar persist; invalid changes are rejected atomically',async()=>{const DB=database();let r=await api(request('','profile'),{DB});const token=r.headers.get('X-Obitel-Session');r=await api(request(token,'profile',{name:'Северный',avatar:4}),{DB});assert.equal(r.status,200);r=await api(request(token,'profile'),{DB});let p=await r.json();assert.equal(p.name,'Северный');assert.equal(p.avatar,4);for(const body of [{name:'А'},{name:'<script>'},{name:'Изменён',avatar:99},{avatar:-1}]){r=await api(request(token,'profile',body),{DB});assert.equal(r.status,400)}r=await api(request(token,'profile'),{DB});p=await r.json();assert.equal(p.name,'Северный');assert.equal(p.avatar,4);DB.sqlite.close()});

test('server rejects locked gear and refuses votes items for scrap',async()=>{const DB=database(),uid='a'.repeat(32);const world={players:{[uid]:{name:'Тест',save:{...freshSave(),scrap:999999,cloth:9999,cores:9999}}},raids:{}};DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify(world));let r=await api(request(uid,'weapon',{weapon:8}),{DB});assert.equal(r.status,400);world.players[uid].save.xp=99999999;DB.sqlite.prepare('UPDATE game_world SET data=?').run(JSON.stringify(world));for(const [path,body] of [['weapon',{weapon:9}],['armor',{armor:8}]]){r=await api(request(uid,path,body),{DB});assert.equal(r.status,503)}const after=JSON.parse(DB.sqlite.prepare('SELECT data FROM game_world').get().data);assert.equal(after.players[uid].save.scrap,999999);assert.deepEqual(after.players[uid].save.owned,[0]);r=await api(request(uid,'weapon',{weapon:8}),{DB});assert.equal(r.status,200);assert.equal((await r.json()).save.scrap,999999-16000);DB.sqlite.close()});

test('vehicle ownership and stat changes persist across Worker requests',async()=>{const DB=database(),uid='a'.repeat(32);DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify({players:{[uid]:{name:'Водитель',save:{...freshSave(),xp:240,scrap:2000}}},raids:{}}));let r=await api(request(uid,'vehicle',{vehicle:'spark'}),{DB});assert.equal(r.status,200);let data=await r.json();assert.equal(data.save.scrap,800);assert.equal(data.save.vehicle,'spark');r=await api(request(uid,'vehicle',{vehicle:'spark'}),{DB});assert.equal((await r.json()).save.scrap,800);r=await api(request(uid,'profile'),{DB});assert.equal((await r.json()).save.vehicle,'spark');r=await api(request(uid,'vehicle',{vehicle:'ark'}),{DB});assert.equal(r.status,400);DB.sqlite.close()});

test('raid polling does not rewrite world between presence heartbeats',async()=>{
 const DB=database(),uid='a'.repeat(32),rid='b'.repeat(12);
 const world={players:{[uid]:{name:'Наблюдатель',publicId:'c'.repeat(12),lastSeen:Date.now(),save:freshSave()}},raids:{[rid]:{id:rid,map:0,hp:750,maxHp:750,members:{},created:Date.now()}}};
 DB.sqlite.prepare('INSERT INTO game_world VALUES (?,?,0)').run('beta',JSON.stringify(world));
 const r=await api(request(uid,'raids/'+rid),{DB});assert.equal(r.status,200);assert.equal((await r.json()).raid.hp,750);
 assert.equal(DB.sqlite.prepare('SELECT revision FROM game_world').get().revision,0);
 world.players[uid].lastSeen=Date.now()-31000;DB.sqlite.prepare('UPDATE game_world SET data=?').run(JSON.stringify(world));
 assert.equal((await api(request(uid,'raids/'+rid),{DB})).status,200);assert.equal(DB.sqlite.prepare('SELECT revision FROM game_world').get().revision,1);DB.sqlite.close();
});
